#!/usr/bin/env perl
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


### patch_loutre_dbs

use strict;
use warnings;

use Bio::Otter::Lace::Defaults;

{
    my $usage = sub { exec('perldoc', $0) };
    # This do_getopt() call is needed to parse the otter config files
    # even if you aren't giving any arguments on the command line.
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        ) or $usage->();
    
    # Get all the statements from the magic <> filehandle
    $/ = undef;
    my @statements = grep /\w/, split /;\s*\n/, <>;
    $/ = "\n";    
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    foreach my $ds ($cl->get_all_DataSets) {
        printf STDERR "Patching '%s'\n", $ds->name;
        my $dbh = $ds->make_Vega_DBAdaptor->dbc;
        foreach my $sql (@statements) {
            $dbh->do($sql);
        }
    }
}




__END__

=head1 NAME - patch_loutre_dbs

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

