#!/bin/sh

bigwig_get_key_map='
    csver_remote=>csver
    type=>chr
    '

bigwig_get_key_list='
    dataset
    end
    file
    gff_seqname
    gff_source
    gff_version
    start
    strand
    version
    '

exec filter_wrap \
    "$bigwig_get_key_map"   \
    "$bigwig_get_key_list"  \
    bigwig_get "$@"
