#!/usr/bin/env perl
# Copyright [2018-2023] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;
use warnings;

package Bio::Otter::GetScript::DNAGet;

use Bio::EnsEMBL::SimpleFeature;

use base 'Bio::Otter::Utils::GetScript::LocalDB';

sub version { return 'dna_get 0.6'; };
sub log_filename { return 'localdb_log.txt'; }

sub do_it {
    my ($self) = @_;

    $self->do_requires;

    my $slice = $self->vega_slice;
    my $start = $slice->start;
    my $end   = $slice->end;
    my $label = $slice->seq_region_name;

    my $feature = Bio::EnsEMBL::SimpleFeature->new(
            -start         => 1,
            -end           => $slice->length,
            -strand        => 1,
            -slice         => $slice,
            -display_label => $label,
        );

    my $fasta = << "__EO_HEADER__";
##sequence-region $label $start $end
##FASTA
>$label
__EO_HEADER__

    # FIXME: dup with Bio::Otter::Server::GFF
    my $seq   = $feature->seq;
    while ($seq =~ /(.{1,70})/g) {
        $fasta .= $1 . "\n";
    }

    $self->send_feature_gff(
        [ ],                    # no features!
        0,                      # don't process_gff
        \$fasta,
        );

    return;
}

## no critic (Modules::ProhibitMultiplePackages)

package main;

use Log::Log4perl::Level;

Bio::Otter::GetScript::DNAGet
    ->new(log4perl => $DEBUG)
    ->run;

exit;

__END__

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

