#!/usr/bin/env perl
# Copyright [2018-2024] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;
use warnings;

package Bio::Otter::GetScript::LocalDBGet;

use base 'Bio::Otter::Utils::GetScript::LocalDB';

sub version { return 'localdb_get 0.5'; };
sub log_filename { return 'localdb_log.txt'; }

sub do_it {
    my ($self) = @_;

    $self->do_requires;

    $self->set_extra_gff_args( pseudogene_fake_cds => 1 );

    my $features = $self->get_features;
    $self->send_feature_gff($features, 1); # 1 = process_gff

    return;
}

## no critic (Modules::ProhibitMultiplePackages)

package main;

use Log::Log4perl::Level;

Bio::Otter::GetScript::LocalDBGet
    ->new(log4perl => $DEBUG)
    ->run;

exit;

__END__

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

