#!/usr/bin/env perl

use strict;
use warnings;

package Bio::Otter::GetScript::TilePathGet;

use Bio::Vega::Tiler;

use base 'Bio::Otter::Utils::GetScript::LocalDB';

sub version { return 'tilepath_get 0.5'; };
sub log_filename { return 'localdb_log.txt'; }

sub do_it {
    my ($self) = @_;

    $self->do_requires;

    my $cs_name;
    if ($self->vega_slice->adaptor->db->get_CoordSystemAdaptor->fetch_by_name('contig')) {
      $cs_name = 'contig';
    }
    else {
      $cs_name = 'seqlevel';
    }
    my $tiler = Bio::Vega::Tiler->new($self->vega_slice);
    my @features = $tiler->simple_features($cs_name);
    $self->send_feature_gff(\@features);

    return;
}

## no critic (Modules::ProhibitMultiplePackages)

package main;

use Log::Log4perl::Level;

Bio::Otter::GetScript::TilePathGet
    ->new(log4perl => $DEBUG)
    ->run;

exit;

__END__

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

