#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any GET request

use strict;
use Bio::Otter::ServerScriptSupport;
use Bio::Otter::CloneFinder; # pipehead==0 version
use Bio::Vega::CloneFinder;  # pipehead==1 version

$| = 1;

my $server = Bio::Otter::ServerScriptSupport->new(
    'dataset','qnames','type','maxpipehits','unhide');

my $qnames       = $server->require_argument('qnames');
my $filter_atype = $server->getarg('type')   || '';
my $unhide       = $server->getarg('unhide') || 0;

my $odba = $server->otter_dba();

my $finder_class = $pipehead
    ? 'Bio::Vega::CloneFinder'
    : 'Bio::Otter::CloneFinder';

my $finder = $finder_class->new($odba, [ split(',', $qnames) ]);

$finder->find($unhide);

my $output_string = $finder->generate_output($filter_atype);

$server->send_response($output_string, 1);

1;

