#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any GET request

use strict;
use OtterDefs;
use Bio::Otter::ServerQuery;
use Bio::Otter::ServerSide (':all');
use Bio::Otter::CloneFinder; # pipehead==0 version
use Bio::Vega::CloneFinder;  # pipehead==1 version

$| = 1;

my $sq = Bio::Otter::ServerQuery->new('dataset','qnames','type','maxpipehits','unhide');
set_nph($sq);

my $qnames = $sq->getarg('qnames') || error_exit($sq, "No 'qnames' argument entered");
my $filter_atype = $sq->getarg('type') || '';
my $unhide = $sq->getarg('unhide') || 0;

my $odba = get_DBAdaptor_from_CGI_species($sq, $OTTER_SPECIES, $pipehead);

my $finder_class = $pipehead
    ? 'Bio::Vega::CloneFinder'
    : 'Bio::Otter::CloneFinder';

my $finder = $finder_class->new($odba, [ split(',', $qnames) ]);

$finder->find($unhide);

my $output_string = $finder->generate_output($filter_atype);

send_response($sq, $output_string, 1);

1;

