#!/usr/local/bin/perl -w

use strict;
use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText ('%OrderOfOptions');

my $server = Bio::Otter::ServerScriptSupport->new('dataset',
    'cs','csver','name','type','start','end','strand',
    'metakey','analysis');

my $analysis_name = $server->getarg('analysis') || undef; # defaults to 'all analyses'
my $metakey       = $server->getarg('metakey')  || '';    # defaults to pipeline

my $sfs = $server->fetch_mapped_features('simple_feature',
            ['get_all_SimpleFeatures', $analysis_name] );

my @sf_optnames = @{ $OrderOfOptions{SimpleFeature} };

my $output_string = '';

foreach my $sf (@$sfs) {
        # output a SimpleFeature line
    my @sf_optvalues = ('SimpleFeature');
    for my $opt (@sf_optnames) {
        push @sf_optvalues, $sf->$opt();
    }

    if(!$analysis_name) {
        push @sf_optvalues, $sf->analysis()->logic_name();
    }

    $output_string .= join("\t", @sf_optvalues)."\n";
}

$server->send_response($output_string, 1);

1;

