#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any GET request

use strict;
use OtterDefs;
use Bio::Otter::ServerQuery;
use Bio::Otter::ServerSide (':all');
use Bio::Otter::Lace::PipelineDB;
use Bio::EnsEMBL::DBSQL::DBAdaptor;
use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::ToXML;

$| = 1;

my $sq = Bio::Otter::ServerQuery->new('dataset',
    'cs','csver','name','type','start','end','strand',
    'metakey','analysis','transcript_analyses');
set_nph($sq);

my $cs       = $sq->getarg('cs')      || 'chromosome';
my $csver    = $sq->getarg('csver')   || undef;
my $analysis = $sq->getarg('analysis');
my $metakey  = $sq->getarg('metakey') || ''; # defaults to pipeline
my $transcript_analyses = $sq->getarg('transcript_analyses') || '';

my $allowed_transcript_analyses_hash = $transcript_analyses
    ? { map { $_ => 1 } split(/,/, $transcript_analyses) }
    : '';

my $odba = get_DBAdaptor_from_CGI_species($sq, $OTTER_SPECIES, $pipehead);
my $sdba = odba_to_sdba($sq, $odba, $pipehead, $metakey);

my ($mdba, $sdba_asm) = get_mapper_dba($sq, $odba, $sdba, $pipehead);

my $genes = [];

if($mdba) {
#    server_log("Assembly mapping not implemented yet");
#    send_response($sq, '', 1);
#    exit(0);

    my $local_slice   = get_slice($sq, $mdba, $pipehead);
    my $proj_segments = $local_slice->project( $cs, $sdba_asm );

    my $sa = $sdba->get_SliceAdaptor();

    foreach my $segment (@$proj_segments) {
        my $projected_slice = $segment->to_Slice();

        my $foreign_slice = $sa->fetch_by_region(
            $projected_slice->coord_system()->name(),
            $projected_slice->seq_region_name(),
            $projected_slice->start(),
            $projected_slice->end(),
            $projected_slice->strand(),
            $projected_slice->coord_system()->version(),
        );

        foreach $foreign_gene (@{ $foreign_slice->get_all_Genes($analysis) }) {
            push @$genes, $foreign_gene->transform($cs, $csver);
        }
    }

} else {
    $original_slice = get_slice($sq, $sdba, $pipehead);
    $genes = $original_slice->get_all_Genes($analysis);
}

server_log("Total of ".scalar(@$genes)." '$analysis' genes found");

my $output_string = '';

foreach my $gene (@$genes) {
    $output_string .= $gene->toXMLstring($allowed_transcript_analyses_hash);
}

send_response($sq, $output_string, 1);

