#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any GET request

use strict;
use OtterDefs;
use Bio::Otter::ServerQuery;
use Bio::Otter::ServerSide (':all');

$| = 1;

my $sq = Bio::Otter::ServerQuery->new('dataset','which','key');
set_nph($sq);

my $which = $sq->getarg('which') || 'otter';
my $key   = $sq->getarg('key');

my $dba = get_DBAdaptor_from_CGI_species($sq, $OTTER_SPECIES, $pipehead);
if($which eq 'pipe') {
    $dba = odba_to_sdba($sq, $dba, $pipehead);
}
my $dbc = $pipehead ? $dba->dbc() : $dba;

my $sth = $dbc->prepare(qq{
    SELECT meta_key, meta_value
      FROM meta
}.($key ? qq{   WHERE meta_key = '$key' } : '')
.qq{
  ORDER BY meta_id
});
$sth->execute;

my $counter = 0;
my $output_string ='';

while (my ($meta_key, $meta_value) = $sth->fetchrow) {

    $meta_value=~s/\s+/ /g; # get rid of newlines and tabs

    $output_string .= join("\t", $meta_key, $meta_value)."\n";
    $counter++;
}

server_log("Total of $counter meta table pairs sent");

send_response($sq, $output_string, 1);

