#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any request

use strict;
use OtterDefs;
use Bio::Otter::ServerQuery;
use Bio::Otter::ServerSide (':all');
use Bio::Otter::DBSQL::DBAdaptor;

$| = 1;

my $sq = Bio::Otter::ServerQuery->new('dataset','type','author');
set_nph($sq);

my $odba = get_DBAdaptor_from_CGI_species($sq, $OTTER_SPECIES, $pipehead);
my $odbc = $pipehead ? $odba->dbc() : $odba;

my $asm_type = $sq->getarg('type');
my $aut_name = $sq->getarg('author');

my $sql = $pipehead
? qq{
    SELECT cl.name, concat(cl.embl_acc, '.', cl.embl_version), ctg.name,
           l.hostname, l.timestamp, aut.author_name, aut.author_email
      FROM seq_region cl,
           seq_region ctg,
           assembly cl2ctg,
           seq_region_attrib embl_acc, seq_region_attrib embl_version }
.($asm_type ? qq{ , assembly chr2ctg, seq_region chr } : '')
.qq{
 LEFT JOIN contig_lock l ON ctg.seq_region_id = l.seq_region_id
 LEFT JOIN author aut ON aut.author_id = l.author_id
     WHERE cl2ctg.asm_seq_region_id=cl.seq_region_id
       AND cl2ctg.cmp_seq_region_id=ctg.seq_region_id
       AND cl.coord_system_id=(select coord_system_id from coord_system where name='clone')
       AND ctg.coord_system_id=(select coord_system_id from coord_system where name='contig')
       AND embl_acc.seq_region_id=cl.seq_region_id
       AND embl_acc.attrib_type_id=(select attrib_type_id from attrib_type where code='embl_accession')
       AND embl_version.seq_region_id=cl.seq_region_id
       AND embl_version.attrib_type_id=(select attrib_type_id from attrib_type where code='embl_version') }
.($asm_type ? qq{
       AND chr.name = "$asm_type"
       AND chr2ctg.asm_seq_region_id=chr.seq_region_id
       AND chr2ctg.cmp_seq_region_id=ctg.seq_region_id } : '' )
.($aut_name ? qq{ AND aut.author_name = "$aut_name" } : '')
.qq{
       AND l.contig_lock_id IS NOT NULL
  ORDER BY l.timestamp
}
: qq{
    SELECT cl.name, concat(cl.embl_acc, '.', cl.embl_version), ctg.name,
           l.hostname, l.timestamp, aut.author_name, aut.author_email
      FROM clone cl,
           contig ctg }
.($asm_type ? qq{ , assembly asm } : '' )
.qq{
 LEFT JOIN clone_lock l ON cl.clone_id = l.clone_id
 LEFT JOIN author aut ON aut.author_id = l.author_id
    WHERE ctg.clone_id = cl.clone_id
}
.($asm_type ? qq{ AND asm.contig_id = ctg.contig_id AND asm.type = "$asm_type" } : '')
.($aut_name ? qq{ AND aut.author_name = "$aut_name" } : '')
.qq{
       AND l.clone_lock_id IS NOT NULL
  ORDER BY l.timestamp
};

my $sth = $odbc->prepare($sql);
$sth->execute();

my $output_string = '';
while (my (@columns) = $sth->fetchrow()) {
    $output_string .= join("\t", @columns)."\n";
}

send_response($sq, $output_string, 1);

