#!/usr/local/bin/perl -w

my $pipehead = $ENV{PIPEHEAD}; # is set by the server for any GET request

use strict;
use Bio::Otter::ServerSide (':all');
use Bio::Otter::Lace::ViaText ('%OrderOfOptions');

$| = 1;

my $sq = Bio::Otter::ServerQuery->new('dataset',
    'cs','csver','name','type','start','end','strand',
    'metakey','analysis','ditype');
set_nph($sq);

if(!$pipehead) {
    error_exit($sq, "This kind of data is only available from new API databases. Set pipehead to 1");
}

my $analysis = $sq->getarg('analysis');
my $ditype   = $sq->getarg('ditype');

my $dfs = fetch_mapped_features($sq, $pipehead, 'ditag_feature', 
            ['get_all_DitagFeatures', $ditype, $analysis] );

server_log("Total of ".scalar(@$dfs)
          .($ditype ? " <$ditype>":'')
          .($analysis ? " {$analysis}":'')
          ." ditag features found");

my @df_optnames = @{ $OrderOfOptions{DitagFeature} };
my @do_optnames = @{ $OrderOfOptions{DitagObject} };
my $output_string = '';

    # Stringify only the simple fields:
my %do_seen = (); # collect the seen ditag object ids here

foreach my $df (@$dfs) {

    my $do = $df->ditag(); # object
    my $do_id = $do->dbID();

    if(!exists($do_seen{$do_id})) { # a new one

            # output a ditag object line:
        my @do_optvalues = ('DitagObject');
        for my $opt (@do_optnames) {
            push @do_optvalues, $do->$opt() || 0;
        }
        $output_string .= join("\t", @do_optvalues)."\n";

        $do_seen{$do_id}++;
    }

        # output a ditag feature line:
    my @df_optvalues = ('DitagFeature');
    for my $opt (@df_optnames) {
        push @df_optvalues, $df->$opt();
    }
    push @df_optvalues, $do_id;

    $output_string .= join("\t", @df_optvalues)."\n";
}

send_response($sq, $output_string, 1);

