#!/usr/local/bin/perl -w

use OtterDefs;
use strict;

use Bio::Otter::ServerQuery;

use Bio::Otter::CloneLockBroker;
use Bio::Otter::Converter;
use Bio::Otter::Lace::TempFile;

use Bio::Otter::ServerSide qw(:all);


$| = 1;
my $sq = Bio::Otter::ServerQuery->new('dataset',
    'data', 'author', 'email',
);
set_nph($sq);

server_log("******* Starting to unlock region *********");

my $odb    = get_DBAdaptor_from_CGI_species($sq, $OTTER_SPECIES);
my $author = get_Author_from_CGI($sq);

my $xml_data  = $sq->getarg('data') || error_exit($sq, "No xml data entered. Can't write region");
server_log("Length of data " . length($xml_data) );

my $auth_name = $author->name();
my $tmp_xml = Bio::Otter::Lace::TempFile->new;
$tmp_xml->root('/tmp');
$tmp_xml->name(qq`unlock_region_${auth_name}.xml`);
my $tmp_xml_name = $tmp_xml->full_name();
server_log("Writing xml to tmp file [$tmp_xml_name]");

my $xml_fh = eval{
    $tmp_xml->write_file_handle();
} || error_exit($sq, "Can't write to '$tmp_xml_name' : $!");
print $xml_fh $xml_data;

# Save a bit of memory
$xml_data = undef;

server_log("Converting xml to otter...");
my $fh = $tmp_xml->read_file_handle();

####################################################################

my( $genes, $slice );

eval {
    ($genes,$slice) = Bio::Otter::Converter::XML_to_otter($fh, $odb);
    
    my $chrname  = $slice->chr_name;
    my $chrstart = $slice->chr_start;
    my $chrend   = $slice->chr_end;

    server_log("Processed incoming xml file with slice: [$chrname] [$chrstart] [$chrend]");
};
if ($@) {
  error_exit($sq, "Failed converting XML to otter [$@]");
}
server_log("Done converting.");

my $cb   = new Bio::Otter::CloneLockBroker($odb);

server_log("Checking region is locked...");
eval {
  $cb->check_locks_exist_by_slice($slice,$author);
};
if ($@) {
  error_exit($sq, "Failed checking locks [$@]");
}
server_log("Done checking region is locked.");


server_log("Unlocking clones...");
eval{
    $cb->remove_by_slice($slice,$author);
};
error_exit($sq, "Failed to unlock clones") if $@;
server_log("Done unlocking clones.");

####################################################################

send_response($sq, "<response>\n</response>\n", 1);

