#! /bin/sh
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# 1.  amend previous commit, under certain circumstances
# 2.  go to web sandbox and rebuild some branches' Otter Servers


bail() {
    echo "$@" >&2
    exit 2
}

last_minute_ci() {
    if git diff --cached --quiet --exit-code && git diff --quiet --exit-code; then
        echo '(no last-minute changes)'
    else
        AUTH_LAST=$( git log -1 --format=%ae )
        if [ "$AUTH_LAST" != "$( git config user.email )" ]; then
            bail "*** There are last-minute changes, but
  previous author $AUTH_LAST is not me.  Abort."
        elif [[ "$( git log -1 --format=%s )" =~ ^! ]]; then
            echo === Rewrite last commit for last-minute changes ===
            git ci --amend -CHEAD -a
        else
            bail "*** There are last-minute changes, but
  previous commit doesn't want to be modified (comment !~ ^!).  Abort."
        fi
    fi
}

do_notify_Ubuntu() {
    if [ "$retcode" = "0" ]; then
        notify-send -i /usr/share/icons/oxygen/64x64/actions/weather-clear.png \
            Built "Built OK"
    else
        notify-send -i /usr/share/icons/oxygen/64x64/status/weather-storm.png \
            "BUILD FAIL" "Return code $retcode"
    fi
}


last_minute_ci

# this is good only for sandbox.  dev & staging boxes have no NFS!
ssh web-ottersand-01 "cd $PWD && BUILD_VSNS=\"$*\" /www/$USER/www-dev/otter_server_build.sh"
retcode=$?

if [ "$( lsb_release -is )" = 'Ubuntu' ]; then
    do_notify_Ubuntu
else
    printf "\n\n\n*** No notify mechanism here.  retcode=%s\n\n\n" $retcode
fi
exit $retcode
