#!/usr/local/bin/perl -Tw

# Author:        jh13
# Group:         anacode
# Maintainer:    jh13

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl61 otter55 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_response(
    sub {
        die $INC{q(SangerWeb.pm)};
    });
