#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_response(
    sub {
        my ($server) = @_;
        my $user = $server->authorized_user;
        return $user;
    });

__END__

=head1 NAME - authenticate_me

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

