#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl74 otter79 };

use Bio::Otter::Server::Support::Web;

Bio::Otter::Server::Support::Web->send_response(
    sub {
        my ($server) = @_;
        my $user = $server->authorized_user;
        return $user;
    });

__END__

=head1 NAME - authenticate_me

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

