#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter56 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::CloneFinder;

Bio::Otter::ServerScriptSupport->send_response(
    sub {
        my ($server) = @_;
        my $finder = Bio::Vega::CloneFinder->new($server);
        $finder->find;
        my $output = $finder->generate_output;
        return $output;
    });
