#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl61 otter54 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::CloneFinder;

my $server = Bio::Otter::ServerScriptSupport->new;

my $finder = Bio::Vega::CloneFinder->new($server);
$finder->find;
my $output = $finder->generate_output;

$server->send_response($output, 1);

1;

