#!/usr/local/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Utils::MM;

Bio::Otter::ServerScriptSupport->send_response(
    sub {
        my ($server) = @_;

        my $accs = $server->param('accessions');
        my $acc_list = [ split(/,/, $accs) ];

        my $types;
        eval {
            my $mm = Bio::Otter::Utils::MM->new;
            $types = $mm->get_accession_types($acc_list);
            1;
        } or die "Failed to fetch accession type info: $@";

        my $response = '';
        foreach my $acc (keys %$types) {
            $response .= join("\t", $acc, @{$types->{$acc}}) . "\n";
        }

        return $response;
    });

1;
