#!/usr/local/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl64 otter60 };

use Bio::Otter::Server::GFF::Genes;

Bio::Otter::Server::GFF::Genes->send_requested_features;
