#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl73 otter77 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::ServerAction::XML::Region;

sub get_region {
    my ($server) = @_;
    my $xml = Bio::Otter::ServerAction::XML::Region->new_with_slice($server)->get_region;
    return $xml;
}

Bio::Otter::ServerScriptSupport->send_response(\&get_region);

__END__

=head1 NAME - get_assembly_dna

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk
