#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_file("methods.ace");

__END__

=head1 NAME - get_methods_ace

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

