#!/usr/local/bin/perl -Tw


# Author:        jh13
# Group:         anacode
# Maintainer:    jh13

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl57 otter54 };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Utils::MM;

my $server = Bio::Otter::ServerScriptSupport->new;
my $feature = $server->param('feature');

my $mm = Bio::Otter::Utils::MM->new;
my $details = $mm->get_feature_details($feature);

my $response = join "", map {
    sprintf "%s\t%s\n", $_, $details->{$_};
} keys %{$details};

$server->send_response($response);

1;
