#!/usr/bin/perl -Tw

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 otter };
use Bio::Otter::Git qw{ :server_ensembl :match };

use Bio::Otter::Server::Support::Web;
use Bio::Otter::ServerAction::LoutreDB;

sub get_meta {
    my ($server) = @_;
    return Bio::Otter::ServerAction::LoutreDB->new($server)->get_meta;
}

Bio::Otter::Server::Support::Web->send_response(-content_type => 'application/json', \&get_meta);

__END__

=head1 NAME - get_meta

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk
