#!/usr/bin/perl -Tw

# Author:        anacode
# Group:         anacode
# Maintainer:    anacode

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl72 otter76 };

use Bio::Otter::ServerScriptSupport;

my $select_cs_sql = <<'SQL';
    SELECT coord_system_id, species_id, name, version, rank, attrib
      FROM coord_system
     WHERE name = 'chromosome' AND version = 'Otter'
SQL

sub get_db_info {
    my ($server) = @_;

    my $sth = $server->otter_dba()->dbc()->prepare($select_cs_sql);
    $sth->execute;
    my @cs_chromosome = $sth->fetchrow;

    my $output_string = join("\t", 'coord_system.chromosome', @cs_chromosome) . "\n";

    return $server->otter_wrap_response($output_string);
}

Bio::Otter::ServerScriptSupport->send_response(\&get_db_info);

__END__

=head1 NAME - get_config

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

