#!/usr/local/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_file("otter_styles.ini");

__END__

=head1 NAME - get_otter_styles

=head1 AUTHOR

Graham Ritchie B<email> gr5@sanger.ac.uk



