#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl66 otter71 };

use DBI;

use Bio::Otter::ServerScriptSupport;

sub get_species {
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $user = $server->authorized_user;
    my $dbh = DBI->connect('DBI:mysql:host=cbi5d.internal.sanger.ac.uk', 'genero', undef);
    my $taxon_id_string = $server->require_argument('taxon_id_list');
    my @taxon;
    foreach my $tid (split /,/, $taxon_id_string) {
        $tid =~ s/\D+//g;
        push(@taxon, $tid);
    }

    return "User '$user' is fetching taxonomy info for (@taxon)";
}

Bio::Otter::ServerScriptSupport->send_response(\&get_species);

__END__

=head1 NAME - get_species

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

