#!/usr/bin/perl -Tw

# Author:        mg13
# Group:         anacode
# Maintainer:    mg13

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl72 otter76 };

use Bio::Otter::Server::GFF::PslSql;

Bio::Otter::Server::GFF::PslSql->send_requested_features;
