#!/software/bin/perl

# Author: mca
#
# Wrapper script on old nph-foo scripts, for migration away from nph.
# We don't want to be maintaining two copies of these scripts while
# the clients are switched over.

use strict;
use warnings;
# require nothing


sub main {
    $ENV{PATH} = "/bin";
    my $script = scriptpath_nph();
    { exec($script); } # {}s to avoid Perl warning
    print "Status: 500\n\n$0 failed to exec($script): $!\n";
}

sub scriptpath_nph {
    my $script = $ENV{SCRIPT_FILENAME} || $0;
    if ($script =~ m{^(/[-_a-zA-Z0-9/]+)/([-_a-zA-Z0-9]+)$}) {
	return "$1/nph-$2";
    } else {
	print "Status: 500\n\nFailed to untaint and derive nph- name for $script\n";
	exit(1);
    }
}

main();
