#!/usr/local/bin/perl -Tw

# Author:        lg4
# Group:         anacode
# Maintainer:    lg4

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl57 otter54 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText qw( %LangDesc &GenerateFeatures );

my $server       = Bio::Otter::ServerScriptSupport->new;

my $output_string;

eval {
    my $analysis_list = $server->param('analysis');
    my $features = $server->get_requested_features;
    $output_string = GenerateFeatures($features, $analysis_list);
};

if ($@) {
    $server->error_exit($@);
} else {
    $server->send_response($output_string, 1);
}

1;

