#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl73 otter78 };

use Bio::Otter::Server::Support::Web;
use Bio::Otter::ServerAction::TSV::LoutreDB;

sub get_meta {
    my ($server) = @_;
    my $tsv = Bio::Otter::ServerAction::TSV::LoutreDB->new($server)->get_meta;
    return $server->otter_wrap_response($tsv);
}

Bio::Otter::Server::Support::Web->send_response(\&get_meta);

__END__

=head1 NAME - get_meta

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk
