#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::Transform::XML;

sub get_region {
    my ($server) = @_;

my $trunc  = $server->param('trunc');
my $odba  = $server->otter_dba();
my $slice = $server->get_requested_slice;

warn "Converting slice to XML...\n";

my $formatter = Bio::Vega::Transform::XML->new;
$formatter->skip_truncated_genes($trunc ? 0 : 1);
$formatter->otter_dba($odba);
$formatter->slice($slice);
$formatter->fetch_data_from_otter_db;
my $xml = $formatter->generate_OtterXML;

warn "Done converting slice to XML. Length of XML = " . length($xml) . "\n";

    return $xml;
}

Bio::Otter::ServerScriptSupport->send_response(\&get_region);

1;

