#!/usr/local/bin/perl -Tw

# Author:        jh13
# Group:         anacode
# Maintainer:    jh13

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl61 otter55 };

use Bio::Otter::ServerScriptSupport;

my $mapping_none_xml = <<'XML'
  <mapping>
    <none></none>
  </mapping>
XML
    ;

sub mapping_none_xml {
    return $mapping_none_xml;
}

my $mapping_equiv_xml_format = <<'XML'
  <mapping>
    <equiv>
      <local>
        <seq_region>%s</seq_region>
        <coord_system>%s</coord_system>
      </local>
      <remote>
        <seq_region>%s</seq_region>
        <coord_system>%s</coord_system>
      </remote>
    </equiv>
  </mapping>
XML
    ;

sub mapping_equiv_xml {
    my $xml = sprintf $mapping_equiv_xml_format, @_;
    return $xml;
}

sub get_mapping {
    my ($server) = @_;

    my $dataset = $server->require_argument('dataset');
    my $local_seq_region = $server->require_argument('sr');
    my $local_coord_system = $server->require_argument('cs');

    my $output_string =
        ( ($dataset eq 'mouse'
           && $local_seq_region eq 'chr12-04'
           && $local_coord_system eq 'Otter'
          )
          ? mapping_equiv_xml(
              $local_seq_region, $local_coord_system,
              '4', 'NCBIm37',
          )
          : mapping_none_xml
          );

    return $server->otter_wrap_response($output_string);
}

Bio::Otter::ServerScriptSupport->send_response(\&get_mapping);

1;

