#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl66 otter71 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::ServerAction::Region;

sub get_assembly_dna {
    my ($server) = @_;

    my $params = $server->require_arguments(@Bio::Otter::ServerAction::Region::REQUIRED_PARAMS);
    my $sa_region = Bio::Otter::ServerAction::Region->new_with_slice($server, $params);

    return $sa_region->get_assembly_dna;
}

Bio::Otter::ServerScriptSupport->send_response(\&get_assembly_dna);

__END__

=head1 NAME - get_assembly_dna

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

