#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl64 otter62 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_file("otter_config");

__END__

=head1 NAME - get_otter_config

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

