#!/usr/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl73 otter77 };

use Bio::Otter::Server::GFF::Genes;

Bio::Otter::Server::GFF::Genes->send_requested_features;
