#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl59 otter54 };

use Bio::Otter::ServerScriptSupport;

{
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $tar = $server->data_dir . "/lace_acedb.tar.gz";
    open my $TAR_FH, '<', $tar or
        $server->error_exit("Error getting empty acedb database directory structure\nCan't read '$tar' : $!");

    print $server->header(
        -status => 200,
        -type   => 'application/x-tar-gzip',
        );
    while (<$TAR_FH>) {
        print;
    }
    close $TAR_FH;  # Too late for error to client
}


__END__

=head1 NAME - get_lace_acedb_tar

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

