#!/usr/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl70 otter72 };

use Bio::Otter::ServerScriptSupport;

Bio::Otter::ServerScriptSupport->send_file("otter_styles.ini");

__END__

=head1 NAME - get_otter_styles

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

