#!/usr/bin/perl -Tw

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 otter81 };
use Bio::Otter::Git qw{ :server_ensembl :match };

use Bio::Otter::Server::GFF;

Bio::Otter::Server::GFF->send_requested_features;
