#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl74 otter79 };

use Bio::Otter::Server::Support::Web;
use Bio::Otter::ServerAction::Region;

sub get_assembly_dna {
    my ($server) = @_;

    my $sa_region = Bio::Otter::ServerAction::Region->new_with_slice($server);

    return $sa_region->get_assembly_dna;
}

Bio::Otter::Server::Support::Web->send_response(\&get_assembly_dna);

__END__

=head1 NAME - get_assembly_dna

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

