#!/usr/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl67 otter72 };

use Bio::Otter::Server::GFF::DAS;

Bio::Otter::Server::GFF::DAS->send_requested_features;
