#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter54 };

use Bio::Otter::ServerScriptSupport;

my $select_meta_sql = <<'SQL'
    SELECT meta_key, meta_value
      FROM meta
  ORDER BY meta_id
SQL
    ;

sub get_meta {
    my ($server) = @_;

    my $sth = $server->otter_dba()->dbc()->prepare($select_meta_sql);
    $sth->execute;

    my $counter = 0;
    my $output_string ='';
    while (my ($meta_key, $meta_value) = $sth->fetchrow) {
        $meta_value=~s/\s+/ /g; # get rid of newlines and tabs
        $output_string .= join("\t", $meta_key, $meta_value)."\n";
        $counter++;
    }

    warn "Total of $counter meta table pairs sent\n";

    return $server->otter_wrap_response($output_string);
}

Bio::Otter::ServerScriptSupport->send_response(\&get_meta);

1;

