#!/usr/local/bin/perl -Tw

# Author:        jh13
# Group:         anacode
# Maintainer:    jh13

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl61 otter55 };

use Bio::Otter::Server::GFF;

Bio::Otter::Server::GFF->send_response(
    sub {
        my ($server) = @_;

        my $type  = $server->param('type');
        my $start = $server->param('start');
        my $end   = $server->param('end');

        my $gff = '';

        sub do_gff_line {
            chomp;
            my @fields = split /\t/;
            next unless scalar @fields == 9;
            next unless 1
                && $fields[0] eq '17'
                && $fields[3] >= $start
                && $fields[4] <= $end
                ;
            $fields[0] = $type;
            $gff .= (join "\t", @fields) . "\n";
            return;
        }

        my $gff_file = "/nfs/users/nfs_j/jh13/work/m_musculus.NCBIm37.vr.best.gtf";
        open my $gff_h, '<', $gff_file
            or die sprintf "failed to open GFF file '%s'", $gff_file;
        while (<$gff_h>) { do_gff_line; }
        close $gff_h or die sprintf "failed to close GFF file '%s'", $gff_file;

        return $server->gff_header . $gff;
    });
