#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl65 otter70 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::ServerAction::Slice;

sub lock_region {
    my ($server) = @_;

    my $params = $server->require_arguments(@Bio::Otter::ServerAction::Slice::REQUIRED_PARAMS);
    $params->{cl_host} = $server->param('hostname') || $ENV{REMOTE_ADDR};

    my $slice = Bio::Otter::ServerAction::Slice->new($server, $params);

    return $slice->lock_region;
}

Bio::Otter::ServerScriptSupport->send_response(\&lock_region);
