#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl73 otter77 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::ServerAction::XML::Region;

sub lock_region {
    my ($server) = @_;

    my $sa_region = Bio::Otter::ServerAction::XML::Region->new_with_slice($server);
    my $xml = $sa_region->lock_region;

    return $xml;
}

Bio::Otter::ServerScriptSupport->send_response(\&lock_region);
