#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2010-02-09 17:23:17 $
# Id:            $Id: nph-authenticate_me,v 1.14 2010-02-09 17:23:17 jh13 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-authenticate_me,v $

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl56 otter52 };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;
my $user = $server->authorized_user;
$server->send_response($user);


__END__

=head1 NAME - nph-authenticate_me

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

