#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-04-25 09:50:19 $
# Id:            $Id: nph-get_species,v 1.4 2008-04-25 09:50:19 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_species,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl48 otter49 };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;



__END__

=head1 NAME - nph-get_species

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

