#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-05-29 15:43:49 $
# Id:            $Id: nph-get_align_features,v 1.16 2008-05-29 15:43:49 lg4 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_align_features,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl49 otter49 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText::ToText ('&GenerateAlignFeatures');

my $server = Bio::Otter::ServerScriptSupport->new;

my $output_string = '';

eval {
    my $analysis_name = $server->param('analysis') || undef; # which means 'all analyses'
    my $kind          = $server->param('kind');

    my $method = {
        'dafs' => 'get_all_DnaAlignFeatures',
        'pafs' => 'get_all_ProteinAlignFeatures',
    }->{$kind};

    my $afs = $server->fetch_mapped_features('align_feature', $method, [$analysis_name],
        map { defined($server->param($_)) ? $server->param($_) : '' } qw(cs name type start end metakey csver csver_remote)
    );

        # Fetch the hit descriptions from the pipeline:
    my $pdbc = $server->satellite_dba( '' )->dbc();

    $output_string = GenerateAlignFeatures($afs, $analysis_name, $pdbc);
};

if ($@) {
    $server->error_exit($@);
} else {
    $server->send_response($output_string, 1);
}

1;
