#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2007-09-18 09:33:33 $
# Id:            $Id: nph-get_sequenceset_accesslist,v 1.4 2007-09-18 09:33:33 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_sequenceset_accesslist,v $

use strict;
use SangerPaths qw{ otter48 ensembl46 bioperl123 core };

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;

my $dataset = $server->require_argument('dataset');
my $odba    = $server->otter_dba();

$server->fetch_Author_obj($server->authorized_user);  # will break if author cannot be fetched

my $sth=$odba->prepare(q{
            SELECT ssa.assembly_type
              , ssa.access_type
              , au.author_name
            FROM sequence_set_access ssa
              , author au
            WHERE ssa.author_id = au.author_id
});
$sth->execute;
my $xml = '';
$xml   .= qq`  <dataset name="$dataset">\n`;
$xml   .= qq`    <accesslist>\n`;
while (my ($set_name, $access, $author) = $sth->fetchrow) {
  $access = ($access eq 'RW') ? 1 : 0;
  $xml   .= qq`    <access>\n`;
  $xml   .= qq`      <author>$author</author>\n`;
  $xml   .= qq`      <sequenceset_name>$set_name</sequenceset_name>\n`;
  $xml   .= qq`      <access_type>$access</access_type>\n`;
  $xml   .= qq`    </access>\n`;
}
$xml   .= qq`    </accesslist>\n`;
$xml .= qq`  </dataset>\n`;
$server->send_response($xml, 1);

__END__

=head1 NAME - get_sequenceset_accesslist

=head1 DESCRIPTION

return xml for sequence set access list

=head1 AUTHOR

Sindhu K. Pillai B<email> sp1@sanger.ac.uk

