#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2009-07-17 13:41:23 $
# Id:            $Id: nph-get_region,v 1.17 2009-07-17 13:41:23 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_region,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl53 otter52 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::Transform::XML;

my $server = Bio::Otter::ServerScriptSupport->new;

my $cs     = $server->param('cs')     || 'chromosome';
my $csver  = $server->param('csver')  || (($cs eq 'chromosome') ? 'Otter' : undef);
my $name   = $server->require_argument('name');
my $type   = $server->require_argument('type');
my $start  = $server->require_argument('start');
my $end    = $server->require_argument('end');
my $strand = $server->param('strand') || undef;

$server->log("Getting slice... [$name | $type] [$start] [$end]");

my $odba  = $server->otter_dba();
my $slice = $server->get_slice($odba, $cs, $name, $type, $start, $end, $strand, $csver);

$server->log("Converting slice to XML...");

my $formatter = Bio::Vega::Transform::XML->new;
$formatter->otter_dba($odba);
$formatter->slice($slice);
$formatter->fetch_data_from_otter_db;
my $xml = $formatter->generate_OtterXML;

$server->log("Done converting slice to XML. Length of XML = " . length($xml) );

$server->send_response("$xml\n");

1;

