#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2009-02-20 10:50:20 $
# Id:            $Id: nph-show_mapping,v 1.16 2009-02-20 10:50:20 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-show_mapping,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl51 otter52 };

use Bio::Otter::ServerScriptSupport;


my $server = Bio::Otter::ServerScriptSupport->new;

my $dataset   = $server->param('dataset');
my $csver_cmp = $server->param('csver') || ($dataset=~/mouse/ ? 'NCBIM37' : 'NCBI36');
my $csver_asm = 'Otter';
my $mapper_metakey = "mapper_db.${csver_cmp}";

my $odba = $server->otter_dba();

my ($mapper_val) = @{$odba->get_MetaContainer()->list_value_by_key($mapper_metakey)};
my $mdba;

if(!$mapper_val) {
    $server->error_exit("'$mapper_metakey' is not properly defined");
} elsif($mapper_val eq '=otter_head') {
    $mdba = $odba;
} elsif($mapper_val eq '=pipeline_head') {
    $mdba = $server->satellite_dba( '' );
} else {
    $mdba = $server->satellite_dba($mapper_metakey);
}

my $mdbc = $mdba->dbc();
my $output_string = '';

my $sth = $mdbc->prepare(qq{
    SELECT asm.name, cmp.name, a.asm_start, a.asm_end, a.cmp_start, a.cmp_end
    FROM assembly a, seq_region asm, seq_region cmp, coord_system cs_asm, coord_system cs_cmp
    WHERE a.asm_seq_region_id=asm.seq_region_id
    AND a.cmp_seq_region_id=cmp.seq_region_id
    AND cs_asm.version='$csver_asm'
    AND cs_cmp.version='$csver_cmp'
    AND asm.coord_system_id in (cs_asm.coord_system_id, cs_cmp.coord_system_id)
    AND cmp.coord_system_id in (cs_asm.coord_system_id, cs_cmp.coord_system_id)
    ORDER BY asm.name, a.asm_start
});
$sth->execute;
while (my ($asm_name, $cmp_name, $asm_start, $asm_end, $cmp_start, $cmp_end) = $sth->fetchrow) {
    $output_string .= "$asm_name($asm_start..$asm_end) <-- $cmp_name($cmp_start..$cmp_end)\n";
}

$server->send_response($output_string, 1);

1;

