#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2009-06-24 12:50:34 $
# Id:            $Id: nph-get_species,v 1.12 2009-06-24 12:50:34 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_species,v $

use strict;
use DBI;
use SangerPaths qw{ core bioperl123 ensembl53 otter52 };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;
{
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $user = $server->authorized_user;
    my $dbh = DBI->connect('DBI:mysql:host=cbi3.internal.sanger.ac.uk', 'genero', undef);
    my $taxon_id_string = $server->require_argument('taxon_id_list');
    my @taxon;
    foreach my $tid (split /,/, $taxon_id_string) {
        $tid =~ s/\D+//g;
        push(@taxon, $tid);
    }
    $server->send_response("User '$user' is fetching taxonomy info for (@taxon)");
}


__END__

=head1 NAME - nph-get_species

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

