#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2007-09-27 13:22:08 $
# Id:            $Id: nph-test,v 1.5 2007-09-27 13:22:08 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-test,v $

use CGI::Carp 'fatalsToBrowser';

use strict;
use SangerPaths qw{ otter48 ensembl46 bioperl123 core };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;
my $web = SangerWeb->new({
    'cgi'   => $server,
    });

my $user = $web->username;

my $env = "ENV:\n";
foreach my $var (sort keys %ENV) {
    $env .= sprintf "%24s  %s\n", $var, $ENV{$var};
}

$env .= "\nCGI param:\n";
foreach my $var ($server->param) {
    $env .= sprintf "%24s  %s\n", $var, $server->param($var);
}

$env .= sprintf "\nSangerWeb cgi = %s\n", $web->cgi;
$env .= sprintf "\nSangerWeb username = %s\n", $web->username;

if ($ENV{'localuser'} eq 'localuser') {
    $server->send_response($env);
} else {
    $server->send_response("You are an external user\n");
}
