#!/usr/local/bin/perl -Tw

# Author:        lg4
# Group:         anacode
# Maintainer:    lg4
# Last modified: $Date: 2010-03-16 10:58:56 $
# Id:            $Id: nph-get_features,v 1.16 2010-03-16 10:58:56 jh13 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_features,v $

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl56 otter53 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText qw( %LangDesc &GenerateFeatures );

my $server       = Bio::Otter::ServerScriptSupport->new;

my $output_string;

eval {
    my $analysis_list = $server->param('analysis');
    my $features = $server->get_requested_features;
    $output_string = GenerateFeatures($features, $analysis_list);
};

if ($@) {
    $server->error_exit($@);
} else {
    $server->send_response($output_string, 1);
}

1;

