#!/usr/local/bin/perl -Tw

# Author:        gr5
# Group:         anacode
# Maintainer:    gr5

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl56 otter53 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::Utils::EnsEMBL2GFF;

use CGI::Carp 'fatalsToBrowser';

my $server = Bio::Otter::ServerScriptSupport->new;

my $gff_string = '';

eval {
    my $analyses = $server->param('analysis');
    my $types = $server->param('kind');
 
    my $features = $server->get_requested_features;
   
    if (@$features) {
        my $slice = $features->[0]->slice;
        $gff_string = $slice->to_gff(
            analyses        => [split /,/, $analyses], 
            feature_types   => [map {$_.'s'} split /,/, $types],
            include_header  => 1,
        );
    }
};

if ($@) {
	$server->error_exit($@);
}
else {
    $server->send_response($gff_string);
}

1;

