#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2009-06-24 12:50:34 $
# Id:            $Id: nph-get_methods_ace,v 1.11 2009-06-24 12:50:34 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_methods_ace,v $

### nph-get_methods_ace

use strict;

use SangerPaths qw{ core bioperl123 ensembl53 otter52 };

use Bio::Otter::ServerScriptSupport;

{
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $methods_ace = $server->data_dir . "/methods.ace";
    open my $ACE_FH, $methods_ace or
        $server->error_exit("Error getting methods.ace\nCan't read '$methods_ace' : $!");
    local $/ = undef;
    my $ace_txt = <$ACE_FH>;
    $server->send_response($ace_txt);
    close $ACE_FH;  # Too late for error to client
}




__END__

=head1 NAME - nph-get_methods_ace

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

