#!/usr/local/bin/perl -Tw


# Author:        gr5
# Group:         anacode
# Maintainer:    gr5
# Last modified: $Date: 2010-03-16 10:58:56 $
# Id:            $Id: nph-get_accession_types,v 1.23 2010-03-16 10:58:56 jh13 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_accession_types,v $

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl56 otter53 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Utils::MM;

my $server = Bio::Otter::ServerScriptSupport->new;

my $accs = $server->param('accessions');

my @acc_list = split /,/, $accs;

my $mm = Bio::Otter::Utils::MM->new;

my $types = $mm->get_accession_types(\@acc_list);

my $response = '';

for my $key (keys %$types) {
	$response .= $key."\t".$types->{$key}->[0]."\t".$types->{$key}->[1]."\n";
}

$server->send_response($response);

1;
