#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-06-18 17:08:54 $
# Id:            $Id: nph-get_repeat_features,v 1.17 2008-06-18 17:08:54 lg4 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_repeat_features,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl49 otter50 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText ('&GenerateFeatures');

my $server = Bio::Otter::ServerScriptSupport->new;

my $output_string = '';

eval {
    my $analysis_name = $server->param('analysis');

    my $rfs = $server->fetch_mapped_features('repeat_feature', 'get_all_RepeatFeatures', [$analysis_name],
        map { defined($server->param($_)) ? $server->param($_) : '' } qw(cs name type start end metakey csver csver_remote)
    );

    $output_string = GenerateFeatures($rfs, $analysis_name);
};

if ($@) {
    $server->error_exit($@);
} else {
    $server->send_response($output_string, 1);
}

1;

