#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-05-28 18:41:37 $
# Id:            $Id: nph-get_repeat_features,v 1.14 2008-05-28 18:41:37 lg4 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_repeat_features,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl49 otter49 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText::ToText ('&GenerateRepeatFeatures');

my $server = Bio::Otter::ServerScriptSupport->new;

my $analysis_name = $server->param('analysis');

my $rfs = $server->fetch_mapped_features('repeat_feature', 'get_all_RepeatFeatures', [$analysis_name],
    map { defined($server->param($_)) ? $server->param($_) : '' } qw(cs name type start end metakey csver csver_remote)
);

my $output_string = GenerateRepeatFeatures($rfs, $analysis_name);

$server->send_response($output_string, 1);

1;

