#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-06-03 14:09:45 $
# Id:            $Id: nph-get_simple_features,v 1.16 2008-06-03 14:09:45 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_simple_features,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl49 otter50 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::Lace::ViaText::ToText ('&GenerateSimpleFeatures');

my $server = Bio::Otter::ServerScriptSupport->new;

my $output_string = '';

eval {
    my $analysis_name = $server->param('analysis') || undef; # defaults to 'all analyses'

    my $sfs = $server->fetch_mapped_features('simple_feature', 'get_all_SimpleFeatures', [$analysis_name],
        map { defined($server->param($_)) ? $server->param($_) : '' } qw(cs name type start end metakey csver csver_remote)
    );

    $output_string = GenerateSimpleFeatures($sfs, $analysis_name);
};

if ($@) {
    $server->error_exit($@);
} else {
    $server->send_response($output_string, 1);
}

1;

