#!/usr/local/bin/perl -w

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-02-06 11:06:22 $
# Id:            $Id: nph-get_lace_acedb_tar,v 1.2 2008-02-06 11:06:22 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_lace_acedb_tar,v $

### nph-get_lace_acedb_tar

use strict;

use SangerPaths qw{ core bioperl123 ensembl46 otter49 };

use Bio::Otter::ServerScriptSupport;

{
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $tar = $server->data_dir . "/lace_acedb.tar.gz";
    open my $TAR_FH, $tar or
        $server->error_exit("Error getting empty acedb database directory structure\nCan't read '$tar' : $!");

    print $server->header(
        -status => 200,
        -type   => 'application/x-tar-gzip',
        );
    while (<$TAR_FH>) {
        print;
    }
    close $TAR_FH;  # Too late for error to client
}


__END__

=head1 NAME - nph-get_lace_acedb_tar

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

