#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-08-04 15:07:10 $
# Id:            $Id: nph-find_clones,v 1.14 2008-08-04 15:07:10 lg4 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-find_clones,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl49 otter51 };

use Bio::Otter::ServerScriptSupport;
use Bio::Vega::CloneFinder;

my $server = Bio::Otter::ServerScriptSupport->new;

my $qnames       = $server->require_argument('qnames');
my $filter_atype = $server->param('type')   || '';
my $unhide       = $server->param('unhide') || 0;

my $finder = Bio::Vega::CloneFinder->new( $server->otter_dba(), [ split(',', $qnames) ], $unhide);

$finder->find();

my $output_string = $finder->generate_output($filter_atype);

$server->send_response($output_string, 1);

1;

