#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2008-02-22 14:31:28 $
# Id:            $Id: nph-get_clonesequences,v 1.8 2008-02-22 14:31:28 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_clonesequences,v $

use strict;
use SangerPaths qw{ core bioperl123 ensembl46 otter48 };

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;

my $dataset      =  $server->require_argument('dataset');
my $sequenceset  =  $server->require_argument('sequenceset');

my $odba = $server->otter_dba();

# Allow local scripts to access without authorization
unless ($server->local_user) {
    $server->authorized_user;
}


my $xml = '';
$xml   .= qq`  <dataset name="$dataset">\n`;
$xml   .= qq`    <sequenceset name="$sequenceset">\n`;
$xml   .= qq`      <clonesequences>\n`;

if($server->running_headcode()) {

    my $la    = $odba->get_ContigLockAdaptor;
    my $slice = $odba->get_SliceAdaptor()->fetch_by_region('chromosome',$sequenceset,undef,undef,undef,'Otter');
    my $chrs  = $slice->get_all_Attributes('chr')->[0] || $server->error_exit("unknown chromosome name");

    my $chr_name = $chrs->value();
    my $chr_length=$slice->length;

  foreach my $seg (@{ $slice->project('contig') }) {

	 my $contig_asm_start = $seg->from_start;
	 my $contig_asm_end   = $seg->from_end;
	 my $contig_slice     = $seg->to_Slice();

	 my $contig_cmp_start = $contig_slice->start;
	 my $contig_cmp_end   = $contig_slice->end;
	 my $contig_name      = $contig_slice->seq_region_name;
	 my $contig_strand    = $contig_slice->strand;
	 my $contig_length    = $contig_slice->seq_region_length;
	 my $contig_id        = $contig_slice->get_seq_region_id();
	 my $clone_slice      = $contig_slice->project('clone')->[0]->to_Slice;

     my $accs = $clone_slice->get_all_Attributes('embl_acc')->[0];
	 my $accession  = $accs ? $accs->value() : die "unknown clone accession";
	 my $vers = $clone_slice->get_all_Attributes('embl_version')->[0];
     my $version    = $vers ? $vers->value() : die "unknown clone version";
     my $icns = $clone_slice->get_all_Attributes('intl_clone_name')->[0];
	 my $clone_name = $icns ? $icns->value() : $clone_slice->seq_region_name;

	 $xml .= qq`        <clonesequence>\n`;
	 $xml .= qq`          <clone_name>$clone_name</clone_name>\n`;
	 $xml .= qq`          <accession>$accession</accession>\n`;
	 $xml .= qq`          <sv>$version</sv>\n`;
	 $xml .= qq`          <contig_name>$contig_name</contig_name>\n`;
	 $xml .= qq`          <length>$contig_length</length>\n`;
	 $xml .= qq`          <chr name="$chr_name" length="$chr_length"></chr>\n`;
	 $xml .= qq`          <chr_start>$contig_asm_start</chr_start>\n`;
	 $xml .= qq`          <chr_end>$contig_asm_end</chr_end>\n`;
	 $xml .= qq`          <contig_start>$contig_cmp_start</contig_start>\n`;
	 $xml .= qq`          <contig_end>$contig_cmp_end</contig_end>\n`;
	 $xml .= qq`          <contig_strand>$contig_strand</contig_strand>\n`;

	 if(my $contig_lock=$la->fetch_by_contig_id($contig_id)) {
		my $hostname=$contig_lock->hostname;
		my $author_name=$contig_lock->author->name;
		my $author_email=$contig_lock->author->email;
		my $lock_id=$contig_lock->dbID;
		$xml .= qq`          <lock lock_id="$lock_id" author_name="$author_name" email="$author_email" host_name="$hostname"> </lock>\n`;
	 }
	 $xml .= qq`        </clonesequence>\n`;
  }

} else {

    my $sth = $odba->prepare(q{
            SELECT c.name, c.embl_acc, c.embl_version
              , ctg.name, ctg.length
              , ch.name, ch.length, a.chr_start, a.chr_end
              , a.contig_start, a.contig_end, a.contig_ori
              , l.clone_lock_id, l.hostname
              , aut.author_name, aut.author_email
           FROM assembly a
              , contig ctg 
              , clone c
              , chromosome ch
            LEFT JOIN clone_lock l ON l.clone_id = c.clone_id
            LEFT JOIN author aut ON aut.author_id = l.author_id
            WHERE a.contig_id = ctg.contig_id
              AND ctg.clone_id = c.clone_id
              AND ch.chromosome_id = a.chromosome_id
              AND a.type = ?
            ORDER BY a.chr_start 
                });
    $sth->execute($sequenceset);
    while (my ($name, $acc,  $sv,
           $ctg_name,  $ctg_length,
           $chr_name, $chr_length, $chr_start,  $chr_end,
           $ctg_start, $ctg_end, $ctg_strand,
           $clone_lock_id, $hostname,
           $author_name, $author_email ) = $sth->fetchrow) {

      $xml .= qq`        <clonesequence>\n`;
      $xml .= qq`          <clone_name>$name</clone_name>\n`;
      $xml .= qq`          <accession>$acc</accession>\n`;
      $xml .= qq`          <sv>$sv</sv>\n`;
      $xml .= qq`          <contig_name>$ctg_name</contig_name>\n`;
      $xml .= qq`          <length>$ctg_length</length>\n`;
      $xml .= qq`          <chr name="$chr_name" length="$chr_length"></chr>\n`;
      $xml .= qq`          <chr_start>$chr_start</chr_start>\n`;
      $xml .= qq`          <chr_end>$chr_end</chr_end>\n`;
      $xml .= qq`          <contig_start>$ctg_start</contig_start>\n`;
      $xml .= qq`          <contig_end>$ctg_end</contig_end>\n`;
      $xml .= qq`          <contig_strand>$ctg_strand</contig_strand>\n`;
      if (defined $clone_lock_id){
        $xml .= qq`          <lock lock_id="$clone_lock_id" author_name="$author_name" email="$author_email" host_name="$hostname"> </lock>\n`;
      }
      $xml .= qq`        </clonesequence>\n`;
    }

} # if old API

$xml .= qq`      </clonesequences>\n`;
$xml .= qq`    </sequenceset>\n`;
$xml .= qq`  </dataset>\n`;

$server->send_response($xml, 1);

1;

__END__

=head1 NAME - get_clonesequences


=head1 DESCRIPTION

return xml for Clone Sequences of a sequence set.

=head1 AUTHOR

Sindhu K.Pillai B<email> sp1@sanger.ac.uk
Leo Gordon B<email> lg4@sanger.ac.uk
