#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2007-09-18 09:33:33 $
# Id:            $Id: nph-get_meta,v 1.4 2007-09-18 09:33:33 jgrg Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_meta,v $

use strict;
use SangerPaths qw{ otter48 ensembl46 bioperl123 core };

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;

my $which = $server->param('which') || 'otter';
my $key   = $server->param('key');

my $dba = ($which eq 'pipe')
    ? $server->satellite_dba( '' )
    : $server->otter_dba();

my $dbc = $server->running_headcode() ? $dba->dbc() : $dba;

my $sth = $dbc->prepare(qq{
    SELECT meta_key, meta_value
      FROM meta
}.($key ? qq{   WHERE meta_key = '$key' } : '')
.qq{
  ORDER BY meta_id
});
$sth->execute;

my $counter = 0;
my $output_string ='';

while (my ($meta_key, $meta_value) = $sth->fetchrow) {

    $meta_value=~s/\s+/ /g; # get rid of newlines and tabs

    $output_string .= join("\t", $meta_key, $meta_value)."\n";
    $counter++;
}

$server->log("Total of $counter meta table pairs sent");

$server->send_response($output_string, 1);

1;

