#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2010-02-09 16:46:19 $
# Id:            $Id: nph-get_lace_acedb_tar,v 1.15 2010-02-09 16:46:19 jh13 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-get_lace_acedb_tar,v $

### nph-get_lace_acedb_tar

use strict;

use SangerPaths qw{ core bioperl123 ensembl56 otter52 };

use Bio::Otter::ServerScriptSupport;

{
    my $server = Bio::Otter::ServerScriptSupport->new;
    my $tar = $server->data_dir . "/lace_acedb.tar.gz";
    open my $TAR_FH, '<', $tar or
        $server->error_exit("Error getting empty acedb database directory structure\nCan't read '$tar' : $!");

    print $server->header(
        -status => 200,
        -type   => 'application/x-tar-gzip',
        );
    while (<$TAR_FH>) {
        print;
    }
    close $TAR_FH;  # Too late for error to client
}


__END__

=head1 NAME - nph-get_lace_acedb_tar

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

