#!/usr/bin/perl -Tw

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 otter };
use Bio::Otter::Git qw{ :server_ensembl :match };

use Bio::Otter::Server::Support::Web;
use Bio::Otter::ServerAction::XML::Region;

sub unlock_region {
    my ($server) = @_;
    $server->dataset_assert_write;

    my $sa_region = Bio::Otter::ServerAction::XML::Region->new($server);
    return $sa_region->unlock_region;
}

Bio::Otter::Server::Support::Web->send_response(\&unlock_region);
