#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl72 otter76 };

use Bio::Otter::ServerScriptSupport;
use Bio::Otter::ServerAction::XML::Region;

sub unlock_region {
    my ($server) = @_;

    my $sa_region = Bio::Otter::ServerAction::XML::Region->new($server);
    $sa_region->unlock_region;

    return $server->otter_wrap_response("<response>\n</response>\n");
}

Bio::Otter::ServerScriptSupport->send_response(\&unlock_region);
