#!/usr/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg

use strict;
use warnings;

BEGIN { use lib ($ENV{OTTER_PERL_INC} || q{}) =~ m{([^:]+)}g }
use SangerPaths qw{ core bioperl123 ensembl73 otter78 };

use Bio::Otter::ServerAction::XML::Region;
use Bio::Otter::Server::Support::Web;

sub write_region {
    my ($server) = @_;

    my $sa_region = Bio::Otter::ServerAction::XML::Region->new($server);
    my $output_xml = $sa_region->write_region;

    return $output_xml;
}

Bio::Otter::Server::Support::Web->send_response(\&write_region);
