#!/usr/bin/env perl
# Copyright [2018-2021] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


### add_strain_meta_tags

use strict;
use warnings;

use Bio::Otter::Lace::Defaults;
use Bio::Otter::Server::Config;
use Bio::Otter::Utils::Script::MouseStrains;

{
    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt() or $usage->();

    my $mouse_strains = Bio::Otter::Utils::Script::MouseStrains->new;
    foreach my $code (@{$mouse_strains->new_codes}) {
        my $str = $mouse_strains->by_code($code);
        my $strain = $str->strain_name;
        my $dataset = $str->dataset_name;

        print STDERR "$dataset:\n";
        my $ds = Bio::Otter::Server::Config->SpeciesDat->dataset($dataset);

        add_strain_meta_tag('loutre', $ds->otter_dba,                  $strain);
        add_strain_meta_tag('pipe',   $ds->pipeline_dba('pipe', 'rw'), $strain);
    }
    exit;
}

sub add_strain_meta_tag {
    my ($desc, $dba, $strain) = @_;
    printf STDERR "\t%-6s: species.strain => %s\n", $desc, $strain;
    my $sth = $dba->dbc->prepare(q{
        REPLACE INTO meta (species_id, meta_key, meta_value) VALUES (1, 'species.strain', ?)
    });
    $sth->execute($strain);
    return;
}

__END__

=head1 NAME - add_strain_meta_tags

=head1 AUTHOR

Michael Gray B<email> mg13@sanger.ac.uk
