#!/usr/local/bin/perl -w

use strict;
use Getopt::Long 'GetOptions';
use Bio::Otter::Lace::Defaults;
use DBI;
use Bio::EnsEMBL::RawContig;


my ($dataset, $new_otter_db, $chk_agp, $passwd);

Bio::Otter::Lace::Defaults::do_getopt('ds|dataset=s' => \$dataset,      # otter dset, eg, human or mouse or zebrafish
									  'newdb=s'      => \$new_otter_db, # loutre dbname
									  'agp'          => \$chk_agp,      # if only wants to see which contigs are not in AGP
 									  'pass=s'       => \$passwd
									 );

die "Specify -ds and -newdb and -pass\n" unless ($dataset and $new_otter_db and $passwd);

my $client   = Bio::Otter::Lace::Defaults::make_Client();
my $dset     = $client->get_DataSet_by_name($dataset);	
my $otter_db = $dset->get_cached_DBAdaptor;
my $rca      = $otter_db->get_RawContigAdaptor;

my $ctgs = $rca->fetch_all;
my $ctgID_ctgname; # otter_db contigs

foreach my $ctg (@$ctgs ){
  $ctgID_ctgname->{$ctg->dbID} = $ctg->name;
};

my $new_otter_dbh = DBI->connect("DBI:mysql:$new_otter_db:otterlive:3301", 'ottadmin', $passwd,
						 {RaiseError => 1, AutoCommit => 0}) || die "cannot connect to $new_otter_db, $DBI::errstr";

my $ctgname_2_seqRegionID = convert_ctg_name_2_seq_regon_id($new_otter_dbh);

my $sn = $otter_db->prepare("SELECT * FROM sequence_note");
$sn->execute;

my ($omit, $count_errors, $seen_ctgs, @values, $notes);

while ( my $h = $sn->fetchrow_hashref ) {

  $notes++;
  my $seqReg_id;
  my $ctgname = $ctgID_ctgname->{$h->{contig_id}};

  # only take contignames mapped to a contig_id in otter db
  unless ( $ctgname ){
	$omit .= "contig Id " . $h->{contig_id} . " not in contig table\n";
	$count_errors++;
	next;
  }

  # NO LOADING, only checks which contigs are not in APGs
  if ( $chk_agp ){
	check_agp($ctgname)
  }

  else {
	insert_table($h);
  }
}

print $omit;
print "Found $count_errors sequence_notes have contig_id not in otter contig_table: IGNORED\n";
print "Check that loutre db has ", $notes - $count_errors, " sequence notes entries\n";


#----------------------------------
#           subroutines
#----------------------------------

sub check_agp {

  my $ctgname = shift;

  $seen_ctgs->{$ctgname}++;
  return if $seen_ctgs->{$ctgname} > 1;

  my @msg;
  unless ( $ctgname_2_seqRegionID->{$ctgname} ){
	print "$ctgname not in seq_regon of new otter db\n";
	$ctgname =~ /(.+\.\d+)\.\d+\.\d+/;
	my $acc = $1;

	my @dirs = glob("/nfs/team71/analysis/jgrg/work/human/*");
	foreach my $dir ( @dirs ) {
	  if ( my @found = `ggrep -r $acc $dir/*.agp` ) {
		print @found;
		last;
	  }
	}
  }
}

sub insert_table {

  my $h = shift;

  my $ctg_id     = $h->{contig_id};
  my $seqReg_id  = $ctgname_2_seqRegionID->{$ctgID_ctgname->{$ctg_id}};
  my $author_id  = $h->{author_id};
  my $note_time  = $h->{note_time};
  my $is_current = $h->{is_current};

  # otter enum is diff. from new_otter enum
  ($is_current eq 'Y') ? ($is_current = 'yes') : ($is_current = 'no');

  my $note;
  ($h->{note}) ? ($note = $h->{note}) : ($note = '');

  if ( $seqReg_id ){
	my $insert = $new_otter_dbh->prepare(qq{INSERT IGNORE INTO sequence_note VALUES (?,?,?,?,?)});
	eval {$insert->execute($seqReg_id, $author_id, $note_time, $is_current, $note)};
	$new_otter_dbh->commit;
	$new_otter_dbh->rollback if $@;
  }

  # ignore contignames not mapped to a seq_region_id in loutre db
  else {
    $count_errors++;
	print $ctgID_ctgname->{$ctg_id}," not in $new_otter_db\n";
  }
}

sub convert_ctg_name_2_seq_regon_id {
  my $new_otter_dbh = shift;

  my $qry = $new_otter_dbh->prepare(qq{
                                       SELECT sr.seq_region_id, sr.name
                                       FROM seq_region sr, coord_system cs
                                       WHERE sr.coord_system_id = cs.coord_system_id
                                       AND cs.name = 'contig'
									 }
								  );

  my $ctgname_2_seqRegionID = {};
  $qry->execute;
  while ( my ( $seq_region_id, $ctgname ) = $qry->fetchrow ){
	$ctgname_2_seqRegionID->{$ctgname} = $seq_region_id;
  }

  return $ctgname_2_seqRegionID;
}


__END__
