#!/usr/bin/env perl

### ens_db_to_pipe

use strict;
use warnings;
use Term::ReadKey qw{ ReadMode ReadLine };
use File::Basename qw{ dirname };

{
    my $this_dir = dirname($0);

    my $ottroot_passwd = password_prompt('ottroot');
    my $pipe_db_name = "pipe_ens_mouse";
    my $loutre_db_name = "loutre_mouse";
    my $ens_db_name  = 'mus_musculus_core_82_38';

    my $ens_param    = "--host=ens-livemirror --port=3306 --user=ensro";
    my $loutre_param = "--host=otterlive      --port=3324 --user=ottro";
    my $pipe_param   = "--host=mcs17          --port=3322 --user=ottroot --password='$ottroot_passwd'";

    my $loutre = "mysql $loutre_param --database=$loutre_db_name";
    my $pipe   = "mysql $pipe_param";

    # Create empty pipe databases.
    system_do("$pipe --execute='CREATE DATABASE $pipe_db_name'");
    $pipe   .= " --database=$pipe_db_name";

    # Populate with schema from pipe databases.
    system_do("mysqldump --no-data --host=mcs17 --port=3322 --user=ottro pipe_mouse | $pipe");

    # Copy the tables we keep in sync with Ensembl core 
    system_do("mysqldump --no-create-info $loutre_param $loutre_db_name attrib_type external_db misc_set unmapped_reason | $pipe");

    # Copy data (with --no-create-info because we don't want MyISAM databases from ens dbs).
    system_do("mysqldump --no-create-info $ens_param $ens_db_name coord_system seq_region assembly dna meta | $pipe");

    # # Copy repeat data into pipeline database.
    # system_do("mysqldump $ens_param $ens_db_name repeat_feature repeat_consensus | $pipe");
    # system_do(qq{mysqldump --no-create-info --where='logic_name IN ("submit_contig", "repeatmask", "trf", "dust")' $ens_param $ens_db_name analysis | $pipe});
    # system_do(qq{$pipe --execute='UPDATE analysis SET logic_name = "RepeatMasker" WHERE logic_name = "repeatmask"'});
    # system_do(qq{$pipe --execute='UPDATE analysis SET logic_name = "SubmitContig" WHERE logic_name = "submit_contig"'});
    # system_do(qq{mysqldump $ens_param $ens_db_name --where='table_name = "repeat_feature"' meta_coord | $pipe});

    # Link pipeline db to loutre:
    system_do(qq{$this_dir/save_satellite_db -dataset mouse -key pipeline_ens_rw -satdbname $pipe_db_name -sathost mcs17 -satport 3322 -satuser ottadmin -satpass lutralutra});
    system_do(qq{$this_dir/save_satellite_db -dataset mouse -key pipeline_ens -satdbname $pipe_db_name -sathost mcs18 -satport 3322 -satuser ottro});
}

sub system_do {
    my ($command) = @_;

    my $echo_command = $command;
    $echo_command =~ s/--password=\S+/--password=******/;
    print STDERR "$echo_command\n";
    system($command) == 0 or die "Error executing '$echo_command'; exit $?";
}

sub password_prompt {
    my ($user) = @_;

    print STDERR "Password for '$user': ";
    ReadMode('noecho');
    my $password = ReadLine(0);
    print STDERR "\n";
    chomp $password;
    ReadMode('normal');
    return $password;
}




__END__

=head1 NAME - ens_db_to_pipe

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

