#!/usr/bin/env perl

### example_script

use strict;
use warnings;


use Bio::Otter::Lace::Defaults;
use Bio::Otter::Server::Config;

{
    my( $dataset_name );

    my $usage = sub { exec('perldoc', $0) };
    # This do_getopt() call is needed to parse the otter config files
    # even if you aren't giving any arguments on the command line.
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        ) or $usage->();
    $usage->() unless $dataset_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = Bio::Otter::Server::Config->SpeciesDat->dataset($dataset_name);

    my $otter_dba = $ds->otter_dba;
    my $pipe_dba = $ds->pipeline_dba;
    
    my $sth = $otter_dba->dbc->prepare('SELECT (1)');
}



__END__

=head1 NAME - example_script

=head1 SEE ALSO

F<modules/t/obtain-db.t> which exercises various methods of obtaining
a connection.

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

