#!/usr/bin/env perl

### example_script

use strict;
use warnings;


use Bio::Otter::Lace::Defaults;
use Bio::Otter::Lace::PipelineDB;

{
    my( $dataset_name, $set_name );

    my $usage = sub { exec('perldoc', $0) };
    # This do_getopt() call is needed to parse the otter config files
    # even if you aren't giving any arguments on the command line.
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        'set|chr=s'     => \$set_name,
        ) or $usage->();
    $usage->() unless $dataset_name and $set_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    
    # SequenceSet contains a list of CloneSequence objects
    # in the assembly.
    my $ss = $ds->get_SequenceSet_by_name($set_name);
    
    my $otter_dba = $ds->get_cached_DBAdaptor;
    my $pipe_dba = Bio::Otter::Lace::PipelineDB::get_pipeline_DBAdaptor($otter_dba);
    
    my $sth = $otter_dba->dbc->prepare('SELECT (1)');
}



__END__

=head1 NAME - example_script

=head1 SEE ALSO

F<modules/t/obtain-db.t> which exercises various methods of obtaining
a connection.

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

