#!/usr/bin/env perl
# Copyright [2018-2020] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;
use warnings;


# farm_info

# displays essential farm info about hosts(availability, low memory), users' running jobs, etc
# Author: Chao-Kung Chen
# Date  : 2005-03-31

use Getopt::Long 'GetOptions';
use Term::ANSIColor;

my $buser;
GetOptions('u|user=s' => \$buser) or die "command line error";
die "error: usage: farm_info <user>" unless defined $buser;

my $sep = ( '-' x 75 ) . "\n";

my $pipebin = '/usr/local/lsf/7.0/linux2.6-glibc2.3-x86_64/bin';

#--------------------
#    LSF busers
#--------------------

print $sep;
set_color("magenta", "FARM USERS");
print "\n";
printf("%-10s\t%s\t%s\t%s\t%s\t%s\n", "USER", "JOBS", "PEND", "RUN", "SSUSP", "USUSP");

my @busers = `$pipebin/busers all`;

foreach (@busers ) {
  chomp;

  if ( $_ !~ /^(USER|default)/ ){
    my ($user, $c2, $c3, $jobs, $pend, $run, $SSUSP, $USUSP) = split(/\s+/, $_);
    if ( $jobs != 0 ) {
      if ( $user eq $buser ){
        set_color("red", $user);
        $user = '';
      }
      printf("%-10s\t%s\t%s\t%s\t%s\t%s\n", $user, $jobs, $pend, $run, $SSUSP, $USUSP);
    }
  }
}


#--------------------
#     LSF bhosts
#--------------------

print $sep;
set_color("magenta", "HOST STATUS INFO");
print "\n";

my @bhosts = `$pipebin/bhosts`;
my $status_host = {};

foreach ( @bhosts ) {
  chomp;

  if ( $_ !~ /^HOST/ ){
    my ($host, $status) = split(/\s+/, $_);
    if ( $host =~ /^(\w+)-.+/ ){
      $host = $1;
    }
    elsif ( $host =~ /^ecs/ ){
      $host = 'ecs';
    }
    elsif ( $host =~ /^pfam/ ){
      $host = 'pfam';
    }
    $status_host->{$status}->{$host}++;
  }
}

foreach my $status ( keys %$status_host ){
  my $count = 0;
  my $info;
  my $info_s = sprintf("%-10s", $status);
  foreach my $host ( keys %{$status_host->{$status}} ){
    $info .= sprintf("%-5s(%d)\t", $host, $status_host->{$status}->{$host});
    $count += $status_host->{$status}->{$host};
  }
  printf("%s(%d)\t- %s\n", $info_s, $count, $info);

}

#--------------------
#    LSF lsload
#--------------------

print $sep;
set_color("magenta", "HOST LOW /tmp MEM INFO (< 1GB )");
print "\n";

my @lsload = `$pipebin/lsload -R'select[tmp<1000]' -Itmp`;
print "Ie, you are OK\n";
if ( @lsload ) {

  printf("%-10s\t%s\t%s\n", "HOST", "STATUS", "/tmp MEM < 1GB");

  foreach ( @lsload ) {
    chomp;
    if ( $_ !~ /^HOST/ ) {
      my ($host, $status, $tmp) = split(/\s+/, $_);
      printf("%-10s\t%s\t%s\n", $host, $status, $tmp);
    }
  }
}

#--------------------
#     LSF bjobs
#--------------------



my @status = `$pipebin/bjobs -l -u $buser`;
for (@status) {
    s/^\s*//;
    chomp;
}
@status = split(/-{20}/,join("",@status));

# This output format depends on user bsub command and
# works on our current setting
#Job <3684107>, Job Name <human_finished:Est2genome_other>, User <ck1>, Project

my ($db, $logic_name, $status,$queue);
my $db_logic_name_jobs_status = {};

foreach ( @status ) {
  chomp;
  $queue = undef;
  if ( $_ =~ /Job Name <(.+):(\w+)>,.+/ ){
    $db = $1;
    $logic_name = $2;
  }elsif($_ =~ /Job Name <script_(\w+)>,.+Queue <(\w+)>/){
      $db = "rulemanager";
      $logic_name = $1;
      $queue = $2;
  }
  if ( $_ =~ /tatus <(\w+)>,.+/ ){
    my $status = $1;
    $db_logic_name_jobs_status->{$db}{$logic_name}{$status}++;
    $db_logic_name_jobs_status->{$db}{$logic_name}{$status} = $queue if $queue;

  }
}

print $sep;
set_color("magenta", "RULE_MANAGER SCRIPT - user $buser");
print "\n";

printf("%-27s%-25s%-15s%s\n", "SCRIPT", "PIPELINE", "STATUS", "QUEUE");

foreach my $db ( sort keys %$db_logic_name_jobs_status ){
  next unless $db =~ /rule/;
  set_color("cyan", "$db\n");
  foreach my $logicN ( keys %{$db_logic_name_jobs_status->{$db}} ){
    printf("%-27s%-25s", "", $logicN);
    foreach my $status ( keys %{$db_logic_name_jobs_status->{$db}{$logicN}} ){
      printf("%s%s%-15s%s\n","","", $status, $db_logic_name_jobs_status->{$db}{$logicN}{$status});
    }
  }
}

print $sep;
set_color("magenta", "JOBS INFO - user $buser");
print "\n";

printf("%-27s%-25s%-15s%s\n", "DATABASE", "ANALYSIS", "STATUS", "JOBS");


foreach my $db ( sort keys %$db_logic_name_jobs_status ){
  next unless $db !~ /rule/;
  set_color("cyan", "$db\n");
  foreach my $logicN ( keys %{$db_logic_name_jobs_status->{$db}} ){
    printf("%-27s%-25s\n", "", $logicN);
    foreach my $status ( keys %{$db_logic_name_jobs_status->{$db}{$logicN}} ){
      printf("%-27s%-25s%-15s%s\n","","", $status, $db_logic_name_jobs_status->{$db}{$logicN}{$status});
    }
  }
}


sub set_color {

  my ($color, $info) = @_;

  print color($color), "$info";
  print color 'reset';

  return;
}


__END__



lsload -R'select[tmp<100]' -Itmp

will show you which machines currently have less than 100 MB of tmp space free.

If jobs use a lot of tmp space, you should include tmp in your select[] and rusage[] resource requirements.  Say you need a gigabyte, that would mean:

select[tmp>1000] rusage[tmp=1000]

Since you also need a memory requirement, say, 1.5GB, you probably should include mem statements as well, and also a memory limit so that LSF will kill the job if it explodes:

bsub -M 1500000 -R'select[mem>1500 && tmp>1000] rusage[mem=1500:tmp=1000]' ...
