#!/usr/bin/env perl
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use warnings;


### gene_versions

use strict;
use Bio::Otter::Lace::Defaults;

{
    my $dataset_name = 'mouse';

    my $usage = sub { exec('perldoc', $0) };
    # This do_getopt() call is needed to parse the otter config files
    # even if you aren't giving any arguments on the command line.
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        ) or $usage->();
    $usage->() unless $dataset_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    
    my $otter_dba = $ds->get_cached_DBAdaptor;
    my $gene_aptr = $otter_dba->get_GeneAdaptor;
    
    foreach my $gsid (@ARGV) {
        print "\n";
        my $gene = $gene_aptr->fetch_by_stable_id($gsid);
        print gene_summary($gene);
        my $version = $gene->version;
        for (my $i = $version - 1; $i > 0; $i--) {
            my $gene = $gene_aptr->fetch_by_stable_id_version($gsid, $i);
            print gene_summary($gene);
        }
    }
}

sub gene_summary {
    my ($gene) = @_;
    
    my $name = $gene->gene_info->name->name;
    my $sid = $gene->stable_id;
    my $version = $gene->version;
    my $type = $gene->type;
    return "$sid.$version $type $name\n";
}



__END__

=head1 NAME - gene_versions

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

