#!/usr/local/bin/perl -w

### get_softmasked_seq_for_set

use strict;

use Bio::Otter::Lace::Defaults;

{
    my( $dataset_name, $set_name );

    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        'set|chr=s'     => \$set_name,
        ) or $usage->();
    $usage->() unless $dataset_name and $set_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    
    # SequenceSet contains a list of CloneSequence objects
    # in the assembly.
    my $ss = $ds->get_SequenceSet_by_name($set_name);
    $ds->fetch_all_CloneSequences_for_SequenceSet($ss);
    # $ds->fetch_pipeline_ctg_ids_for_SequenceSet($ss);
    
    my $otter_dba = $ds->get_cached_DBAdaptor;
    my $pipe_dba = Bio::Otter::Lace::PipelineDB::get_pipeline_DBAdaptor($otter_dba);
    my $ctg_aptr = $pipe_dba->get_RawContigAdaptor;

    my $cs_list = $ss->CloneSequence_list;
    
    
    my $seq_out = Bio::SeqIO->new(
        -fh     => \*STDOUT,
        -format => 'fasta',
        );
    
    my $repeat_mask = ['trf', 'RepeatMask'];
    my $soft = 1;
    foreach my $cs (@$cs_list) {
        # my $ctg_id = $cs->pipeline_contig_id or die "No pipeline contig ID";
        my $ctg_name = $cs->contig_name();
        my $ctg = $ctg_aptr->fetch_by_name($ctg_name);
        my $seq = $ctg->get_repeatmasked_seq($repeat_mask, $soft);
        $seq_out->write_seq($seq);
    }
}




__END__

=head1 NAME - get_softmasked_seq_for_set

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

