#!/usr/local/bin/perl -w

### otter_embl_dump_test

=pod

=head1 NAME - otter_embl_dump_test

=head1 COMMAND LINE PARAMETERS

Required parameters
  -dataset              
  -chrlibrary_name
  
Optional parameters
  -h|--help

=head1 DESCRIPTION

Test script to for dumping of EMBL files from an
Otter database containing finished genomic sequence
annotation.

One should be able to customise this script to dump
EMBL from Otter for practically any purpose.

Expects acc.sv for the clones to be dumped:

e.g. 

otter_embl_dump_test -dataset human -chr chr1-07 AC114498.2

=cut

use strict;

use Bio::Otter::Lace::Defaults;
use Bio::Otter::EMBL::Factory;
use Carp;

{
    my $dataset_name = undef;
    my $sequence_set = undef;
    
    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'   => $usage,
        'dataset=s' => \$dataset_name,
        'chr|set=s' => \$sequence_set,
        ) or $usage->();
    $usage->() unless $dataset_name and $sequence_set;

    # Connect to Ensembl/Otter database and fetch adaptors
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    my $ds = $cl->get_DataSet_by_name($dataset_name); #Bio::Otter::Lace::DataSet

    my $otter_db = $ds->get_cached_DBAdaptor; #Bio::EnsEMBL::Container
    $otter_db->assembly_type($sequence_set);  #e.g. 'chr1-07'
    
    my $ft_factory = Bio::Otter::EMBL::Factory->new;
    $ft_factory->DataSet($ds);
    
    foreach my $acc (@ARGV) {
        
        my ($accession, $seq_version) = $acc =~ /(^.*)\.(\d+)/ 
            or confess "Error parsing accession and version for: $acc\n";
        
        $ft_factory->entry_name($accession);
        $ft_factory->data_class('standard');
        $ft_factory->mol_type('genomic DNA');
        $ft_factory->division('HUM');
        $ft_factory->ac_star_id('FAKE');
        $ft_factory->organism('Homo sapiens');
        $ft_factory->clone_lib('to_be_provided');
        $ft_factory->clone_name('to_be_provided_2');
        $ft_factory->keywords('HTG');

        my $embl = $ft_factory->embl_setup($accession, $seq_version);
        $ft_factory->make_embl_ft($accession, $embl, $seq_version);
        print $embl->compose();
    }
}


__END__

=head1 NAME - otter_embl_dump_test

=head1 EXAMPLE

  otter_embl_dump_test -dataset human -chr chr1-07 AC114498.2 AL669831.13
  otter_embl_dump_test -dataset human -chr chr11-hsa11_20040402 Z83307 Z95332

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk
Mike Croning B<email> mdr@sanger.ac.uk
