#!/usr/local/bin/perl -w

### productivity_report

use strict;
use Bio::Otter::Lace::Defaults;

{
    my( $dataset_name );

    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        ) or $usage->();
    $usage->() unless $dataset_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    my $otter_dba = $ds->get_cached_DBAdaptor;

    
}



__END__

=head1 NAME - productivity_report

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

