#!/usr/bin/env perl
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use warnings;


### sanger_clone_list_to_acc_sv

use strict;
use Getopt::Long 'GetOptions';
use Bio::Otter::Lace::Defaults;
use Hum::Submission 'accession_from_sanger_name';

{
    my $dataset_name = undef;
    
    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'   => $usage,
        'dataset=s' => \$dataset_name,
        ) or $usage->();
    $usage->() unless $dataset_name;

    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    my $otter_db = $ds->get_cached_DBAdaptor;
    
    my $get_sv = $otter_db->prepare(q{
        SELECT embl_version
        FROM clone
        WHERE embl_acc = ?
        });
    
    while (defined(my $sanger = <>)) {
        chomp($sanger);
        my $acc = accession_from_sanger_name($sanger);
        $get_sv->execute($acc);
        my ($sv) = $get_sv->fetchrow;
        die "No SV for 'acc' ('$sanger')\n" unless $sv;
        print "$acc.$sv\n";
    }
}





__END__

=head1 NAME - sanger_clone_list_to_acc_sv

=head1 SYNOPSIS

  sanger_clone_list_to_acc_sv -dataset <DATASET> <FILE_OF_SANGER_NAMES>

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

