#!/usr/bin/env perl
# Copyright [2018-2021] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use warnings;


### test_all_version_gene_fetch

use strict;
use Bio::Otter::Lace::Defaults;

{
    my( $dataset_name );

    my $usage = sub { exec('perldoc', $0) };
    Bio::Otter::Lace::Defaults::do_getopt(
        'h|help!'       => $usage,
        'dataset=s'     => \$dataset_name,
        ) or $usage->();
    $usage->() unless $dataset_name;
    
    # Client communicates with otter HTTP server
    my $cl = Bio::Otter::Lace::Defaults::make_Client();
    
    # DataSet interacts directly with an otter database
    my $ds = $cl->get_DataSet_by_name($dataset_name);
    my $otter_dba = $ds->get_cached_DBAdaptor;
    
    my $gene_aptr = $otter_dba->get_GeneAdaptor;
    my $sth = $otter_dba->prepare("SELECT gene_id FROM gene");
    $sth->execute;
    
    my $row = 0;
    while (my ($dbID) = $sth->fetchrow) {
        $row++;
        eval{ $gene_aptr->fetch_by_dbID($dbID); };
        warn $@ if $@;
        if ($row % 50) {
            print STDERR ".";
        } else {
            printf STDERR ". %5d\n", $row;
        }
    }
}






__END__

=head1 NAME - test_all_version_gene_fetch

=head1 AUTHOR

Ana Code B<email> anacode@sanger.ac.uk

