#!/usr/local/bin/perl -w

### canvas_text

use strict;
use GenomeCanvas;

{
    my $mw = GenomeCanvas::MainWindow->new;
    $mw->title('Text test');
    $mw->bind(<Control-q>, sub {exit 0});
    $mw->bind(<Control-Q>, sub {exit 0});
    
    my $gc = GenomeCanvas->new($mw);
    
    my $canvas = $gc->canvas;
    $canvas->createRectangle(1,1,500,200,
        -fill       => '#ffffff',
        -outline    => '#999999',
        );
    
    $canvas->eventAdd('<<alpha_num>>', '<KeyPress- >', "a".."z", "A".."Z", 0..9);
    my $size = 15;
    my $x = 10;
    my $y_begin = $x;
    for (my $i = 0; $i < 11; $i++) {
        my $y = $y_begin + ($i * $size + $i);
        my $row_num = $i + 1;
        my $text = "Text in row $row_num";
        make_editable_label($canvas, $x, $y, $text, $size);
    }
    
    $gc->fix_window_min_max_sizes;
    
    Tk::MainLoop();
}

sub make_editable_label {
    my( $canvas, $x, $y, $text, $size ) = @_;
    
    $size ||= 15;
    
    my $t = $canvas->createText(
        $x,$y,
        -anchor => 'nw',
        -text   => $text,
        -font   => ['lucidatypewriter', $size, 'normal'],
        -tags   => ['test text'],
        );
    $canvas->bind($t, '<Enter>',        \&make_text_bold);
    $canvas->bind($t, '<Leave>',        \&make_text_normal);
    $canvas->bind($t, '<BackSpace>',    \&backspace);
    $canvas->bind($t, '<Left>',         \&go_left);
    $canvas->bind($t, '<Right>',        \&go_right);
    $canvas->bind($t, '<<alpha_num>>',  [\&insert_character, Tk::Ev('A')]);
}

BEGIN {

    my $rec_tag = 'SelectedTextBkgd';

    sub backspace {
        my( $canvas ) = @_;

        my $text = $canvas->find('withtag', 'current');

        my $pos = $canvas->index($text, 'insert');
        $canvas->dchars($text, $pos - 1);
    }

    sub go_left {
        my( $canvas ) = @_;

        my $text = $canvas->find('withtag', 'current');

        my $pos = $canvas->index($text, 'insert');
        $canvas->icursor($text, $pos - 1);
    }

    sub go_right {
        my( $canvas ) = @_;

        my $text = $canvas->find('withtag', 'current');

        my $pos = $canvas->index($text, 'insert');
        $canvas->icursor($text, $pos + 1);
    }

    sub make_text_bold {
        my( $canvas ) = @_;

        my $text = $canvas->find('withtag', 'current');

        make_highlight_rectangle($canvas, $text);

        $canvas->focus($text);
        $canvas->icursor($text, 'end');
    }

    sub make_highlight_rectangle {
        my( $canvas, $obj ) = @_;
        
        # Make the highlight rectangle
        my @bbox = $canvas->bbox($obj);
        my $rec = $canvas->createRectangle(
            @bbox,
            -fill       => '#ffff00',
            -outline    => undef,
            -tags       => [$rec_tag],
            );
        $canvas->lower($rec, $obj);
    }

    sub make_text_normal {
        my( $canvas ) = @_;

        $canvas->delete($rec_tag);
        $canvas->focus("");
    }
    
    sub insert_character {
        my( $canvas, $char ) = @_;
        
        my $text = $canvas->find('withtag', 'current');
        $canvas->insert('current', 'insert', $char);
        
        $canvas->delete($rec_tag);
        make_highlight_rectangle($canvas, $text);
    }
}

__END__

=head1 NAME - canvas_text

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

