#!/usr/bin/env perl

use strict;
use warnings;


### example_menucanvas

use MenuCanvasWindow::ExampleWindow;

{
    my $cw = CanvasWindow::MainWindow->new('menu example');
    my $mw = MenuCanvasWindow::ExampleWindow->new($cw);
    $mw->initialize;
    
    Tk::MainLoop();
}




__END__

=head1 NAME - example_menucanvas

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

