#!/usr/local/bin/perl -w

### example_menucanvas

use strict;
use MenuCanvasWindow::Example;

{
    my $cw = CanvasWindow::MainWindow->new('menu example');
    my $mw = MenuCanvasWindow::Example->new($cw);
    $mw->initialize;
    
    Tk::MainLoop();
}




__END__

=head1 NAME - example_menucanvas

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

