#!/usr/bin/env perl
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;
use warnings;


### menu_test

use CanvasWindow;
use Tk::FileSelect;

{
    my $mw = CanvasWindow::MainWindow->new;
    my $menu = $mw->Menu;
    
    my $f_selector = $mw->FileSelect(
        -directory => '/nfs/disk84/jgrg',
        );
    
    $mw->configure(-menu => $menu);
    
    # Chooser menu
    my $chooser = $menu->Menu(
        -tearoff    => 0,
            );
    $menu->add('cascade',
        -label      => 'Chooser',
        -menu       => $chooser,
        -underline  => 0,
        );
    
    $menu->add('separator');
    
    $chooser->add('command',
        -label          => 'Attach ZMap',
        -command        => sub { warn "Called Attach ZMap" },
        -accelerator    => 'Ctrl-X',
        -underline      => 0,
        );
    $chooser->add('command',
        -label          => 'Resync',
        -hidemargin     => 1,
        -command        => sub { warn "Called Resync" },
        -accelerator    => 'Ctrl-R',
        -underline      => 0,
        );
    $chooser->add('command',
        -label          => 'Save As',
        -hidemargin     => 1,
        -command        => sub {
            my $file = $f_selector->Show;
            if ($file) {
                print STDERR "File = '$file'\n";
            } else {
                print STDERR "No file\n";
            }
        },
        -accelerator    => 'Ctrl-S',
        -underline      => 0,
        );
    $chooser->add('separator');
    $chooser->add('command',
        -label          => 'Exit',
        -command        => sub { $mw->destroy },
        -accelerator    => 'Ctrl-Q',
        -underline      => 0,
        );
    
    # Subseq menu
    my $subseq = $menu->Menu(
        -tearoff        => 0,
            );
    $menu->add('cascade',
        -label          => 'SubSeq',
        -menu           => $subseq,
        -underline      => 0,
        -state          => 'disabled',
        );
    
    $subseq->add('command',
        -label          => 'New',
        -command        => sub{ warn "Called New" },
        -accelerator    => 'Ctrl-N',
        -underline      => 0,
        );
    $subseq->add('command',
        -label          => 'Edit',
        -command        => sub{ warn "Called Edit" },
        -accelerator    => 'Ctrl-E',
        -underline      => 0,
        );
    $subseq->add('separator');
    $subseq->add('command',
        -label          => 'Merge',
        -command        => sub{ warn "Called Merge" },
        -accelerator    => 'Ctrl-M',
        -underline      => 0,
        );
    $subseq->add('command',
        -label          => 'AutoMerge',
        -command        => sub{ warn "Called AutoMerge" },
        -accelerator    => 'Ctrl-U',
        -underline      => 0,
        );
    $subseq->add('command',
        -label          => 'Isoform',
        -command        => sub{ warn "Called Isoform" },
        -accelerator    => 'Ctrl-I',
        -underline      => 0,
        );
    $subseq->add('command',
        -label          => 'Transcript',
        -command        => sub{ warn "Called Transcript" },
        -accelerator    => 'Ctrl-T',
        -underline      => 0,
        );
    
    my $cw = CanvasWindow->new($mw);
}

Tk::MainLoop();


__END__

=head1 NAME - menu_test

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

