#!/usr/bin/env perl

use strict;
use warnings;


### notebook_test

use CanvasWindow::MainWindow;
use CanvasWindow;
use Tk::NoteBook;

{
    my $mw = CanvasWindow::MainWindow->new;
    my $nb = $mw->NoteBook->pack(
        -expand => 1,
        -fill   => 'both',
        );
    
    my $cl = $nb->add('clone',
        -label => 'Clone Sequences',
        );

    my $cw1 = CanvasWindow->new($cl);
    my $canvas = $cw1->canvas;
    $canvas->createRectangle(
        0,0, 600,400,
        -fill => 'red',
        -outline => 'white',
        );
    $cw1->fix_window_min_max_sizes;

    my $ss = $nb->add('subseq',
        -label => 'SubSeqs',
        -anchor => 'center',
        );
    
    my $cw2 = CanvasWindow->new($ss);
    my $canvas2 = $cw2->canvas;
    $canvas2->createRectangle(
        0,0, 100,200,
        -fill => 'red',
        -outline => 'white',
        );
    $cw2->set_scroll_region;
    #$cw2->fix_window_min_max_sizes;

    
    my $lo = $nb->add('locus',
        -label => 'Loci',
        -anchor => 'center',
        );
    
    my $cw3 = CanvasWindow->new($lo);
    my $canvas3 = $cw3->canvas;
    $canvas3->createRectangle(
        0,0, 50,100,
        -fill => 'red',
        -outline => 'white',
        );
    $cw3->set_scroll_region;
    #$cw3->fix_window_min_max_sizes;
    
    Tk::MainLoop();
}


__END__

=head1 NAME - notebook_test

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

