#!/usr/bin/env perl
# Copyright [2018-2024] EMBL-European Bioinformatics Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;
use warnings;

### show_acedb_colors

use CanvasWindow;
use Hum::Ace::Colors;

{
    my $mw = CanvasWindow::MainWindow->new;
    $mw->title('acedb colors');
    my $cw = CanvasWindow->new($mw);
    my $canvas = $cw->canvas;

    my $size = 15;
    my $pad = $size / 2;
    my @color_name = Hum::Ace::Colors::list_all_color_names_by_value();
    my $font = ['Helvetica', $size, 'normal'];
    for (my $i = 0; $i < @color_name; $i++) {
        my $name = $color_name[$i];
        my $hex = Hum::Ace::Colors::acename_to_webhex($name);
        warn "$name = $hex\n";
        my $x1 = $size;
        my $x2 = $x1 + $size;
        my $y1 = $size + (($size + $pad) * $i);
        my $y2 = $y1 + $size;
        $canvas->createRectangle(
            $x1, $y1, $x2, $y2,
            -fill       => undef,
            -outline    => $hex,
            );
        
        $canvas->createRectangle(
            $x2 + $pad, $y1, $x2 + $pad + $size, $y2,
            -fill       => $hex,
            -outline    => 'black',
            );
        
        $canvas->createText(
            $x2 + $size + $size, $y1,
            -text   => $name,
            -anchor => 'nw',
            -font   => $font,
            );
    }

    $cw->fix_window_min_max_sizes;

    Tk::MainLoop();
       
}



__END__

=head1 NAME - show_acedb_colors

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

