#!/nfs/humace2/hum/bin/perl -w

### spandit

use strict;
use MenuCanvasWindow::XaceSeqChooser;
use MenuCanvasWindow::ExonCanvas;
use Ace;
use Getopt::Long 'GetOptions';
use Socket;
use vars '@command_line';

{
    @command_line = ($0, @ARGV);
    my ($cript) = $0 =~ m{([^/]+)$};
    my $font_size = 0;
    my($host, $port, $path, $title);
    GetOptions(
        'host=s'        => \$host,
        'port=i'        => \$port,
        'path=s'        => \$path,
        'title=s'       => \$title,
        'fontsize=i'    => \$font_size,
        'h|help!'       => \&useage,
        ) or useage();
    
    if ($path) {
        die "Error: path argument must be an absolute path"
            unless $path =~ m{^/};
        $title ||= "$cript: $path";
    } else {
        useage() unless $host and $port;
        $title ||= "$cript: $host $port";
    }
    
    my $mw = CanvasWindow::MainWindow->new($title);
    my $xc = MenuCanvasWindow::XaceSeqChooser->new($mw);
    $xc->font_size($font_size) if $font_size;
    $xc->clone_list(@ARGV);
     
    if ($path) {
        if (1) {
            $xc->ace_path($path);
        } else {
            #my $local_server = Hum::Ace::LocalServer->new($path);
            my $local_server = Hum::Ace::LocalServer::RPC->new($path);

            $local_server->start_server;
            $xc->local_server($local_server);

            #if (ref($local_server) eq 'Hum::Ace::LocalServer') {
            #    my $sock = $xc->ace_handle->{'database'}->socket;

                ##$sock->sockopt(SO_SNDLOWAT, 1);
                #$sock->sockopt(SO_SNDBUF, 128);
                ##$sock->sockopt(SO_RCVBUF, 128 * 1024);

            #    my %opt_num = (
            #        'SO_SNDLOWAT'   => SO_SNDLOWAT,
            #        'SO_RCVLOWAT'   => SO_RCVLOWAT,
            #        'SO_SNDBUF'     => SO_SNDBUF,
            #        'SO_RCVBUF'     => SO_RCVBUF,
            #        );
            #    foreach my $opt (keys %opt_num) {
            #        my $n = $opt_num{$opt};
            #        print "$opt = ", $sock->sockopt($n), "\n";
            #    }
            #}
        }
    } else {
        my $ace = Ace->connect(
            -HOST       => $host,
            -PORT       => $port,
            -TIMEOUT    => 60,
            ) or die "Can't connect to db on '$host' port '$port' :\n", Ace->error;
        $ace->auto_save(0);
        $xc->ace_handle($ace);
    }
    
    $xc->draw_clone_list;
    $xc->fix_window_min_max_sizes;
    
    my %methods_mutable = (
      # Method name         Mutable?
        supported           => 1,
        supported_CDS       => 1,
        supported_mRNA      => 1,
        GD_supported        => 1,
        GD_supported_mRNA   => 1,
        Pseudogene          => 1,
        fgenesh             => 0,
        FGENES              => 0,
        GENSCAN             => 0,
        HALFWISE            => 0,
        SPAN                => 0,
        EnsEMBL             => 0,
        );
    $xc->set_known_GeneMethods(%methods_mutable);
    
    Tk::MainLoop();
}


sub useage {
    exec('perldoc', $0);
}

__END__

=head1 NAME - spandit

=head1 SYNOPSIS

    spandit -path <ACE DATABASE DIR>
    spandit -host <SERVER> -port <NUMBER>

=head1 DESCRIPTION

B<spandit> (the name is a contraction of "span
edit") is designed to make the creation and
editing of gene structures in an acedb database
as easy as possible.  An aim of the design was to
reduce the number of mouse and keyboard actions
the annotator needs to perform as much as
possible.

spandit has to be manually attached to xace to
work correctly.  This is with the B<Attach Xace>
option in the file menu (or by typing B<Ctrl-X>),
and clicking on the xace main window with the
cross-hairs that appear.  Make sure your xace
main window is visible first!

The main window initailly displays a list of all
the Genome_Sequence objects (B<clones>) which it
finds in the database.  A clone can be selected
with the left mouse button.  More than one can be
selected by pressing B<Shift> when selecting.

=head1 FEATURE

    Sequence
        Exon coordinates
        CDS Start/End
        Start_not_found     CDS_Phase
                            Continues_From
        End_not_found       Continues_As
        Method  Supported
                Supported_CDS
                Supported_mRNA
                Pseudogene
        Remark
        Isoform
    
    Locus
        Name
        Alias
        Type    Pseudogene
                Putative
                Gene    Known
                        Novel_CDS   Human_supported
                                    Non_human_supported
                        Novel_Transcript

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

