#!/usr/local/bin/perl -w

### spandit

use strict;
use XaceSeqChooser;
use ExonCanvas;
use Ace;
use Getopt::Long 'GetOptions';

{
    my ($cript) = $0 =~ m{([^/]+)$};
    my($host, $port, $path, $title);
    GetOptions(
        'host=s'    => \$host,
        'port=i'    => \$port,
        'path=s'    => \$path,
        'title=s'   => \$title,
        'help!'     => \&useage,
        ) or useage();
    
    if ($path) {
        $title ||= "$cript: $path";
    } else {
        useage() unless $host and $port;
        $title ||= "$cript: $host $port";
    }
    
    my $mw = CanvasWindow::MainWindow->new($title);
    my $xc = XaceSeqChooser->new($mw);
    $xc->clone_list(@ARGV);
     
    my( $local_server, $ace );
    if ($path) {
        $local_server = Hum::Ace::LocalServer->new($path);
        $local_server->start_server;
        $xc->local_server($local_server);
    } else {
        $ace = Ace->connect(
            -HOST       => $host,
            -PORT       => $port,
            -TIMEOUT    => 60,
            ) or die "Can't connect to db on '$host' port '$port' :\n", Ace->error;
        $ace->auto_save(0);
        $xc->ace_handle($ace);
    }
    
    $xc->draw_clone_list;
    $xc->fix_window_min_max_sizes;
    
    Tk::MainLoop();
}


sub useage {
    exec('perldoc', $0);
}

__END__

=head1 NAME - spandit

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

