#!/usr/bin/env perl
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


### pfetch

use strict;
use warnings;
use Hum::Pfetch qw{ do_query };

{
    my $query = join(' ', @ARGV) . "\n";
    my $fh = do_query($query);
    while (<$fh>) {
        print;
    }
}


__END__

=head1 NAME - pfetch

=head1 DESCRIPTION

This version of pfetch is only used by otterlace on the Mac when at the Sanger.

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

