#!/usr/local/bin/bash

# Make sure files are group writable
umask 0002

### come find yourself
THISSCRIPT=`basename $0`
   ILIVEIN=`dirname $0` # this is where the script lives. can cd there.
   CVSBASE=..
    CALLED=`pwd`

## get to cvs check outs directory
cd $ILIVEIN/$CVSBASE/..

root=`pwd`

pid_file=$root/ensembl-otter/otter_srv.pid
pid_exist=0

# set PERL5LIB
PERL5LIB=\
$root/ensembl-otter/modules:\
$root/ensembl/modules:\
$root/bioperl-0.7.2

export PERL5LIB

cd ensembl-otter/scripts

# check the pid file exists for later
if [ -e $pid_file ]; then
    pid_exist=1
fi

die(){
    echo "$THISSCRIPT: $1" 1>&2
    exit 1
}
message(){
    echo "$THISSCRIPT: $1"
}

start(){
    if [ "$pid_exist" == "0" ]; then
	message "starting otter_srv..."
        exec ./otter_srv &
    else
	die "can't start '$pid_file' exists"
    fi
}
stop(){
    if [ "$pid_exist" == "1" ]; then
	pid=`cat $pid_file`
	if [ $pid -gt 0 ]; then
	    message "pid exists so stopping $pid"
            kill -INT $pid  2>/dev/null
            if [ "$?" == "0" ]; then
                rm -f $pid_file 2>/dev/null
                pid_exist=0
            else
                die "Failed to 'kill -INT $pid' it is probably not owned by you."
            fi
	else
	    die "'$pid_file' is not a valid pid file"
	fi
    else
	die "no pidfile [$pid_file] exists, so can't stop"
    fi
}
rotate_log(){
    if [ "$pid_exist" == "1" ]; then
	pid=`cat $pid_file`
	if [ $pid -gt 0 ]; then
	    message "rotating logs..."
            kill -HUP $pid 2>dev/null
            if [ "$?" == "0" ]; then
                message "successfully rotated logs."
            else
                die "Failed to 'kill -HUP $pid' it is probably not owned by you."                
            fi
	else
	    die "'$pid_file' is not a valid pid file."
	fi
    else
	die "no pidfile [$pid_file] exists, so can't do rotate."
    fi
}
restart(){
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  logrotate)
    rotate_log
    ;;
  restart)
    restart
    ;;
  *)
    die $"
    Usage: $THISSCRIPT {start|stop|logrotate|restart}"
esac
