#!/usr/local/bin/bash

# Make sure files are group writable
umask 0002

### come find yourself
THISSCRIPT=`basename $0`
   ILIVEIN=`dirname $0` # this is where the script lives. can cd there.
   CVSBASE=..
    CALLED=`pwd`

## get to cvs check outs directory
cd $ILIVEIN/$CVSBASE/..

root=`pwd`
#echo "root=$root"

pid_file=$root/ensembl-otter/otter_srv.pid
pid_exist=0


# set PERL5LIB
PERL5LIB=\
$root/ensembl-otter/modules:\
$root/ensembl/modules:\
$root/bioperl-0.7.2

export PERL5LIB

cd ensembl-otter/scripts

# check the pid file exists for later
if [ -e $pid_file ]; then
    pid_exist=1
fi

start(){
    if [ $pid_exist == 0 ]; then
	echo "starting otter_srv..."
        exec ./otter_srv &
    else
	echo "can't start '$pid_file' exists" 1>&2
    fi
}
stop(){
    if [ $pid_exist == 1 ]; then
	pid=`cat $pid_file`
	if [ $pid > 0 ]; then
	    echo "pid exists so stopping $pid"
            kill -2 $pid
            rm $pid_file
	    pid_exist=0
	else
	    echo "'$pid_file' is not a valid pid file" 1>&2
	    exit 1
	fi
    else
	echo "no pidfile [$pid_file] exists, so can't stop" 1>&2
	exit 1
    fi
}
rotate_log(){
    if [ $pid_exist == 1 ]; then
	pid=`cat $pid_file`
	if [ $pid > 0 ]; then
	    echo "rotating logs..."
            kill -1 $pid
	else
	    echo "'$pid_file' is not a valid pid file." 1>&2
	fi
    else
	echo "no pidfile [$pid_file] exists, so can't do rotate." 1>&2
    fi
}
restart(){
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  logrotate)
    rotate_log
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|logrotate|restart}" 1>&2
    exit 1
esac
