#!/usr/local/bin/perl

use strict;
use Getopt::Long;
use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::Converter;

my $host    = 'ecs1d';
my $user    = 'ensro';
my $pass    = undef;
my $port    = 19322;
my $dbname  = 'otter_chr9p12';

my $chr      = 'virt_chrom_1';
my $chrstart = 1;
my $chrend   = 2000000;
my $type     ='';
my $writedna;

$Getopt::Long::ignorecase=0;

GetOptions(
	   'port:i',    \$port,
	   'pass:s',    \$pass,
	   'host:s',    \$host,
	   'user:s',    \$user,
	   'dbname:s',  \$dbname,
	   
	   'chr:s',     \$chr,
	   'chrstart:i',\$chrstart,
	   'chrend:i',  \$chrend,
	   'type:s',    \$type,
	   'dna',       \$writedna,
	   );


my $db = new Bio::Otter::DBSQL::DBAdaptor(-host   => $host,
	         		          -user   => $user,
				          -pass   => $pass,
				          -port   => $port,
				          -dbname => $dbname);

$db->assembly_type($type);

my $sa = $db->get_SliceAdaptor;

my $slice = $sa->fetch_by_chr_start_end($chr,$chrstart,$chrend);

my $xmlstr = Bio::Otter::Converter::slice_to_XML($slice,$db,$writedna);

print $xmlstr . "\n";
