#!/usr/local/bin/perl

use strict;
use Getopt::Long;

use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::DBSQL::AnnotatedGeneAdaptor;
use Bio::EnsEMBL::DBSQL::DBAdaptor;

use Bio::Otter::Author;
use Bio::Otter::AnnotatedGene;
use Bio::Otter::AnnotatedTranscript;
use Bio::Otter::TranscriptInfo;
use Bio::Otter::GeneInfo;
use Bio::Otter::GeneRemark;
use Bio::Otter::GeneName;
use Bio::Otter::TranscriptRemark;
use Bio::Otter::TranscriptClass;

my $host    = 'ecs1d';
my $user    = 'ensadmin';
my $pass    = 'ensembl';
my $dbname  = 'steve_test_otter_chr6';
my $port    = 19322;

my $otter_host    = 'ecs1d';
my $otter_user    = 'ensadmin';
my $otter_pass    = 'ensembl';
my $otter_port    = 19322;
my $otter_dbname  = 'steve_test_otter_chr6_with_annots';

my $chr      = '6';
my $chrstart = 1;
my $chrend   = 20000000;
my $author;
my $email;

&GetOptions( 'host:s'    => \$host,
             'user:s'    => \$user,
             'pass:s'    => \$pass,
             'port:s'    => \$port,
             'dbname:s'  => \$dbname,
             'otter_host:s'=> \$otter_host,
             'otter_user:s'=> \$otter_user,
             'otter_pass:s'=> \$otter_pass,
             'otter_port:s'=> \$otter_port,
             'otter_dbname:s'  => \$otter_dbname,
             'chr:s'     => \$chr,
             'chrstart:n'=> \$chrstart,
             'chrend:n'  => \$chrend,
	     'author:s'  => \$author,
	     'email:s'   => \$email,
            );


$author || die "No author entered";
$email  || die "No email address entered";

my $ensdb = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host => $host,
					       -user => $user,
					       -pass => $pass,
					       -port => $port,
					       -dbname => $dbname);

my $otterdb = new Bio::Otter::DBSQL::DBAdaptor(-host => $otter_host,
					       -user => $otter_user,
					       -pass => $otter_pass,
					       -port => $otter_port,
					       -dbname => $otter_dbname);

my $oaga = $otterdb->get_AnnotatedGeneAdaptor;


my $sgp = $ensdb->get_SliceAdaptor;


my $vcontig = $sgp->fetch_by_chr_start_end($chr,$chrstart,$chrend);

my $genes = $vcontig->get_all_Genes;

my $author_obj = new Bio::Otter::Author(-name => $author,
					-email => $email);


my $num  = 0;
my $tnum = 0;

foreach my $gene (@$genes) {
    my $class = new Bio::Otter::TranscriptClass(-name => $gene->type,
						-desc => "Ensembl gene");

    my $newgene = bless $gene,"Bio::Otter::AnnotatedGene";

    my $geneinfo = new Bio::Otter::GeneInfo(-gene_stable_id  => $gene->stable_id,
                                             -author    => $author_obj,
                                             -name      => new Bio::Otter::GeneName( -name => $gene->stable_id),
					     );

    $gene->gene_info($geneinfo);

    $num++;
    foreach my $tran (@{$gene->get_all_Transcripts}) {
	bless $tran, "Bio::Otter::AnnotatedTranscript";

	my $ti = Bio::Otter::TranscriptInfo->new(
	-stable_id => $tran->stable_id,
	-name => $tran->stable_id,
	-class => $class,
	-cds_start_not_found => 0,
	-cds_end_not_found => 0,
	-mrna_start_not_found => 0,
	-mrna_end_not_found => 0,
	-author => $author_obj,
						 );

	$tran->transcript_info($ti);

	$tnum++;

        # These lines force loads from the database to stop attempted lazy 
        # loading during the write (which fail because they are to the wrong
        # db) 
        my $get = $tran->translation;
        foreach my $exon (@{$tran->get_all_Exons}) {
          $exon->stable_id;
        }
    }

    # Transform gene to raw contig coords
    $gene->transform;

    #print $gene->toXMLString(),"\n";

    $oaga->store($gene);
}
