#!/usr/local/bin/perl

use strict;
use Getopt::Long;

use Bio::Otter::DBSQL::AnnotatedGeneAdaptor;
use Bio::Otter::DBSQL::DBAdaptor;
use Bio::EnsEMBL::DBSQL::DBAdaptor;

my $host    = 'ecs1c';
my $user    = 'ensro';
my $port    = 3306;
my $pass    = undef;
my $dbname  = 'michele_otter';

my $dna_host   = 'ecs1d';
my $dna_user   = 'ensro';
my $dna_port   = 3306;
my $dna_pass   = undef;
my $dna_dbname = 'homo_sapiens_core_9_30';


my $chr      = '20';
my $chrstart = 1;
my $chrend   = 20000000;

my $clone_accession = undef;
my $output_type = 'xml';

&GetOptions( 
             'host:s'    => \$host,
             'user:s'    => \$user,
             'pass:s'    => \$pass,
             'port:s'    => \$port,
             'dbname:s'  => \$dbname,
             'chr:s'     => \$chr,
             'chrstart:n'=> \$chrstart,
             'chrend:n'  => \$chrend,
             'clone:s'   => \$clone_accession,
             'dna_host:s'=> \$dna_host,
             'dna_user:s'=> \$dna_user,
             'dna_pass:s'=> \$dna_pass,
             'dna_port:s'=> \$dna_port,
             'dna_dbname:s'  => \$dna_dbname,
             'output:s'  => \$output_type,
             );


my $otterdb = new Bio::Otter::DBSQL::DBAdaptor(-host => $host,
					       -user => $user,
					       -pass => $pass,
					       -port => $port,
					       -dbname => $dbname);


my $dnadb = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host => $dna_host,
                                               -user => $dna_user,
                                               -pass => $dna_pass,
                                               -port => $dna_port,
                                               -dbname => $dna_dbname);
$otterdb->dnadb($dnadb);

my $genes;
if (defined($clone_accession)) {
  my $sgp = $otterdb->get_CloneAdaptor;
  my $clone = $sgp->fetch_by_accession($clone_accession);
  $genes = $clone->get_all_Genes;
} else {
  my $sgp = $otterdb->get_SliceAdaptor;
  my $vcontig = $sgp->fetch_by_chr_start_end($chr,$chrstart,$chrend);
  $genes = $vcontig->get_all_Genes;
}

my $oaga = $otterdb->get_AnnotatedGeneAdaptor();

foreach my $gene (@$genes) {

  $oaga->annotate_gene($gene);

  if ($output_type eq 'xml') {
    print $gene->toXMLString() . "\n";
  } elsif ($output_type eq 'ace') {
    print "Not implemented yet\n";
  } else {
    print "Unknown output type $output_type\n";
  }
}
