#!/usr/bin/env perl

use strict;

use OtterDefs;
use DBI;
use Bio::EnsEMBL::DBSQL::DBAdaptor;

my $serverroot = $OTTER_SERVER_ROOT  || die "no OTTER_SERVER_ROOT defined in conf/OtterDefs.pm";
my $dbname     = $OTTER_DBNAME      || die "no OTTER_DBNAME defined in conf/OtterDefs.pm";
my $dbuser     = $OTTER_USER        || die "no OTTER_USER defined in conf/OtterDefs.pm";
my $dbport     = $OTTER_PORT        || die "no OTTER_PORT defined in conf/OtterDefs.pm";
my $dbhost     = $OTTER_HOST        || die "no OTTER_HOST defined in conf/OtterDefs.pm";
my $dbpass     = $OTTER_PASS;

my $ottersql     = $serverroot . "/sql/otter_transact.sql";   #Put these in OtterDefs?s
my $ensemblsql   = $serverroot . "/sql/table_transact.sql";


if (! -e $ottersql)   { die "No otter sql file [$ottersql] exists";}
if (! -e $ensemblsql) { die "No ensembl sql file [$ensemblsql] exists";}

my $passstr = "";

$passstr .= " -p$dbpass" if ($dbpass ne "");

# Test if database exists - exit if so

my $command = "echo create database $dbname | mysql -u $dbuser -h $dbhost -P$dbport $passstr";


run_mysql_command($command,
		  "Error creating database",
		  "Database created successfully",
		  $dbname,
		  $dbhost,
		  $dbuser,
		  $dbpass,
		  $dbport);

$command = "mysql -u $dbuser -h $dbhost $passstr -P$dbport $dbname < $ottersql";

run_mysql_command($command,
		  "Error loading sql file $ottersql",
		  "Sql file $ottersql loaded successfully",
		  $dbname,
		  $dbhost,
		  $dbuser,
		  $dbpass,
		  $dbport);

$command = "mysql -u $dbuser -h $dbhost $passstr -P$dbport $dbname < $ensemblsql";

run_mysql_command($command,
		  "Error loading sql file $ensemblsql",
		  "Sql file $ensemblsql loaded successfully",
		  $dbname,
		  $dbhost,
		  $dbuser,
		  $dbpass,
		  $dbport);




sub run_mysql_command {
  my ($command,$errmessage,$succmessage,$dbname,$host,$user,$pass,$port) = @_;


  my $status = system($command);

  if ($status != 0) {
    print "Status of loading ensembl sql  [$status]\n";
    print "Command run was [$command]\n";
    
    die "$errmessage :  database $dbname on host $host port $port (username $user password $pass)";
    exit(1);
  } else {
    print "Database $dbname on host $host user $user pass $pass $port $port : $succmessage\n";
  }
}
  
