#!/usr/local/bin/perl -w

# Purpose: to install a new otter client distribution
# Author: lg4@sanger.ac.uk

if(scalar(@ARGV)<2) {
	print STDERR "usage:\n";
    print STDERR "\t$0 your_CVS_username new_directory [humpub-release-NN [branch-ensembl-MM]]\n";
	exit 0;
}
my ($user, $new_dir, $otter_tag, $ensembl_tag) = @ARGV;

$otter_tag   ||= 'HEAD';
$ensembl_tag ||= 'HEAD';

# ----------------------------------------------------------------------

my $gzlocation = '/nfs/disk100/humpub/data/dist';

my @gzpacks = ('bioperl-0.7.2', 'bioperl-1.2.3-patched', 'biodas-1.02', 'perl');

my $method = 'checkout'; # ||'export'

my %dir2params = (
	'ace_skeleton'     => ['/nfs/humace2/CVS_master', $otter_tag ],
	'PerlModules'      => ['/nfs/humace2/CVS_master', $otter_tag ],
	'tk'               => ['/nfs/humace2/CVS_master', $otter_tag ],
	'ensembl-ace'      => [":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $otter_tag],
	'ensembl-otter'    => [":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $otter_tag],

	'ensembl'          => [":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", 'branch-ensembl-19'],
	'ensembl-pipeline' => [":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", 'branch-finished-19'],

    'ensembl_head'     => [":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $ensembl_tag, 'ensembl'],
);

# ----------------------------------------------------------------------

mkdir($new_dir);
chdir($new_dir);

foreach my $dir (keys %dir2params) {
    my ($location, $tag, $mod) = @{ $dir2params{$dir} };
    $mod ||= $dir;
	if($location=~/\@/) {
		print "\nPlease enter your CVS password below\n";
	}
	system('cvs', '-d', $location, $method, '-r', $tag, '-d', $dir, $mod);
}

system('cp', (map { 'ace_skeleton/'.$_ } ('methods.ace', 'otter_config', 'oldpipe_otter_config')), '.');
chdir('ace_skeleton');
system('tar', '-cvf', '../lace_acedb.tar', 'database', 'wgf', 'wscripts', 'wspec');
chdir('..');

for my $biodir (@gzpacks) {
    system('cp', $gzlocation.'/'.$biodir.'.tar.gz', '.');
    system('gunzip', $biodir.'.tar.gz');
    system('tar', '-xvf', $biodir.'.tar');
    system('rm', $biodir.'.tar');
}

print STDERR "\nSetting the file permissions...\n";
system('chmod -R g+w *');

# now, the binaries:
for my $dir ('bin', 'bin/LINUXbin') {
    system('mkdir', $dir);
}

print STDERR "\nCopying the binaries...\n";
# system("cp /nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.ALPHA_5/* bin/OSFbin/");
# system("cp /nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.LINUX_4/* bin/LINUXbin/");
# system("cp /nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.DARWIN_4/* bin/MACOSXbin/");

system("cp /nfs/team71/acedb/zmap/BIN.DEVELOPMENT/LINUX/bin/* bin/LINUXbin/");

