#!/usr/bin/env perl

# Purpose: to install a new otter server distribution
# Author: lg4@sanger.ac.uk

use strict;
use warnings;

if(scalar(@ARGV)<2) {
	print STDERR "usage:\n";
	print STDERR "\t$0 your_CVS_username new_directory [humpub-release-NN [branch-ensembl-MM]]\n";
	exit 0;
}
my ($user, $new_dir, $otter_tag, $ensembl_tag) = @ARGV;

# ----------------------------------------------------------------------

my $method = 'checkout'; # || 'export'
my $otter_tagfile = 'CVS_TAG_otter';
my $ensembl_tagfile = 'CVS_TAG_ensembl';

my $gzlocation = '/nfs/disk100/humpub/data/dist';

my @gzpacks = ('bioperl-0.7.2', 'bioperl-1.2.3-patched', 'biodas-1.02');

my @cvs_locations = (
	[":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $method,
		'-r', 'branch-ensembl-19', 'ensembl'],

	[":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $method,
		(defined($otter_tag)?('-r', $otter_tag):()), 'ensembl-otter' ],

	[":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $method,
		(defined($ensembl_tag)?('-r', $ensembl_tag):()), '-d', 'ensembl_head', 'ensembl'],

	[":ext:${user}\@cvs.sanger.ac.uk:/cvsroot/ensembl", $method,
		(defined($ensembl_tag)?('-r', $ensembl_tag):()), '-d', 'ensembl-compara_head', 'ensembl-compara'],
);

# ----------------------------------------------------------------------

mkdir($new_dir);
chdir($new_dir);
$otter_tag ||= 'HEAD';
system("echo $otter_tag > $otter_tagfile");
system("echo $ensembl_tag > $ensembl_tagfile");

foreach my $cvs_location (@cvs_locations) {
	if($cvs_location->[0]=~/\@/) {
		print "\nPlease enter your CVS password below\n";
	}
	system('cvs', '-d', @$cvs_location);
}

for my $biodir (@gzpacks) {
    system('cp', $gzlocation.'/'.$biodir.'.tar.gz', '.');
    system('gunzip', $biodir.'.tar.gz');
    system('tar', '-xvf', $biodir.'.tar');
    system('rm', $biodir.'.tar');
}

system('touch', '.ensemblapi_no_version_check');

system('chmod -R g+w *');

chdir('ensembl-otter/modules');
system('ln -s ../conf/OtterDefs.pm');

