#!/usr/local/bin/perl

use strict;

use Getopt::Long;

use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::DBSQL::AnnotatedGeneAdaptor;
use Bio::Otter::Converter;
use Bio::Otter::Author;

my $host     = '127.0.0.1';
my $user     = 'root';
my $pass     = '';
my $port     = 4444;
my $dbname   = 'otter_9p12';
my $dataset  = 'human_9p12';
my $path     = 'fake_gp_1';

my $dna_host   = '127.0.0.1';
my $dna_user   = 'root';
my $dna_port   = 4444;
my $dna_pass   = undef;
my $dna_dbname = undef;

my $chr;
my $chrstart;
my $chrend;

my $store = 0;
my $print = 0;

my $xmlfile;

my $author_name = `whoami`; chomp($author_name);

my $email = $author_name . "\@sanger.ac.uk";

&GetOptions( 'host:s'    => \$host,
             'user:s'    => \$user,
             'pass:s'    => \$pass,
             'port:s'    => \$port,
             'dbname:s'  => \$dbname,
             'dna_host:s'=> \$dna_host,
             'dna_user:s'=> \$dna_user,
             'dna_pass:s'=> \$dna_pass,
             'dna_port:s'=> \$dna_port,
             'dna_dbname:s'  => \$dna_dbname,
             'chr:s'     => \$chr,
             'chrstart:n'=> \$chrstart,
             'chrend:n'  => \$chrend,
             'xmlfile:s' => \$xmlfile,
             'store'     => \$store,
             'print'     => \$print,
             'dataset:s' => \$dataset,
             'path:s'    => \$path,
             'author:s'  => \$author_name,
             'email:s'   => \$email,
             );

if (!defined($xmlfile)) {
  die("Need an xml file name to read");

}

open(XML,"<$xmlfile") or die "Couldn't open $xmlfile\n";
my $fh = \*XML;

my $odb = new Bio::Otter::DBSQL::DBAdaptor(-host => $host,
                                           -user => $user,
                                           -pass => $pass,
                                           -port => $port,
                                           -dbname => $dbname,
                                           -dataset => $dataset);
if (defined($dna_dbname)) {
  my $dnadb = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host => $dna_host,
                                                 -user => $dna_user,
                                                 -pass => $dna_pass,
                                                 -port => $dna_port,
                                                 -dbname => $dna_dbname);
  $odb->dnadb($dnadb);
}



my $sgp = $odb->get_SliceAdaptor;
my $ga  = $odb->get_GeneAdaptor;
my $ea  = $odb->get_ExonAdaptor;
my $ta  = $odb->get_TranscriptAdaptor;

$odb->assembly_type($path);

my @genes;
my $genes;

my $junk;
($genes,$junk,$junk,$junk) = Bio::Otter::Converter::XML_to_otter($fh);
@genes = @$genes;


if ($print) {
  #print "Printing @genes\n";
  foreach my $gene (@genes) {
    print $gene->toXMLString . "\n";
  }
}
if ($store) {

  print "slice fetched for: ".$chr." ".$chrstart." ".$chrend." on path ".$path."\n";

  my $slice = $sgp->fetch_by_chr_start_end($chr,$chrstart,$chrend);

  my $anal = $odb->get_AnalysisAdaptor()->fetch_by_logic_name('otter');
  my $oaga = $odb->get_GeneAdaptor();


  my $author = new Bio::Otter::Author(-name => $author_name, -email => $email);
  my $time = time;

  foreach my $gene (@genes) {
    print "Stable id " . $gene->stable_id . "\n";

    $gene->adaptor($ga);
    $gene->analysis($anal);
    # NO $gene->type('otter');
    $gene->gene_info->author($author);
    $gene->created($time);
    $gene->modified($time);
    $gene->version(1);

    foreach my $tran (@{$gene->get_all_Transcripts}) {
      $tran->adaptor($ta);
      $tran->transcript_info->author($author);

#HACK (removed)
      # $gene->type("Chr$chr-" . $tran->transcript_info->class->name);

      $tran->created($time);
      $tran->modified($time);
      $tran->version(1);

    }
    foreach my $exon (@{$gene->get_all_Exons}) {

      #$exon->contig($slice);
      $exon->adaptor($ea);
      $exon->created($time);
      $exon->modified($time);
      $exon->version(1);
    }
    my $id = $odb->get_StableIdAdaptor->_fetch_new_by_type('gene','G');
    print "Id $id\n";
    $gene->stable_id($id);
    print "Gene " . $gene->stable_id . "\n";
   
    foreach my $tran (@{$gene->get_all_Transcripts}) {
       if (defined($tran->translation)) {
       #  print "Translate " . $tran->translate->seq . "\n";
       }
       my $id = $odb->get_StableIdAdaptor->_fetch_new_by_type('transcript','T');
       $tran->stable_id($id);
       print "Id $id\n";
       print "Tran " . $tran->stable_id . "\n";
    }
    foreach my $exon (@{$gene->get_all_Exons}) {
       my $id = $odb->get_StableIdAdaptor->_fetch_new_by_type('exon','E');
       $exon->stable_id($id);
       print "Id $id\n";
       print "Exon " . $exon->stable_id . "\n";
    }
    print "Attaching to slice\n";
    $oaga->attach_to_Slice($gene,$slice);
    foreach my $trans (@{$gene->get_all_Transcripts}) {
      if ($trans->translation) {
        #my $id = $odb->get_StableIdAdaptor->_fetch_new_by_type('translation');
        #$trans->translation->stable_id($id);
        if ($trans->translate->seq =~ /\*/) {
          print "Didn't translate\n";
        }else {
          print "Translation = " . $trans->translate->seq . "\n";
        }
      }
    }
    $odb->begin_work;
    $oaga->store($gene);
    $odb->commit;
  }
}
