#!/usr/local/bin/perl
$| = 1;
use strict;
use Getopt::Long;

use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::DBSQL::AnnotatedGeneAdaptor;
use Bio::Otter::Converter;
use Bio::Otter::Author;

my $otterhost     = 'localhost';
my $otteruser     = 'root';
my $otterpass     = '';
my $otterport     = 3306;
my $ottername   = 'test_otter';
my $asstype     = 'test_otter';
my $gap         = 0;
&GetOptions( 'otterhost:s'    => \$otterhost,
             'otteruser:s'    => \$otteruser,
             'otterpass:s'    => \$otterpass,
             'otterport:s'    => \$otterport,
             'asstype:s'      => \$asstype,
             'gap:s'          => \$gap,
            );

  my $odb = new Bio::Otter::DBSQL::DBAdaptor(-host => $otterhost,
                                             -user => $otteruser,
                                             -pass => $otterpass,
                                             -port => $otterport,        
                                             -dbname => $ottername);
  my $ca   = $odb->get_RawContigAdaptor;
  my $chra = $odb->get_ChromosomeAdaptor;

  my $chrstr = "insert into chromosome(chromosome_id,name) values(null,\'CHR\');";

  print $chrstr . "\n";

  my @contigid = $ca->fetch_all_names;

  my $start = 1;

  foreach my $contigid (@contigid) {
     my $contig = $ca->fetch_by_name($contigid);
     my $end = $start + $contig->length -1;

     my $str = "insert into assembly(chromosome_id,chr_start,chr_end,superctg_name,superctg_start,superctg_end,superctg_ori,contig_id,contig_start,contig_end,contig_ori,type) values(1,$start,$end,\'CTG\',$start,$end,1," . 
               $contig->dbID . ",1," . $contig->length . ",1,\'$asstype\');\n";
     print $str;

     $start = $end + $gap + 1;
  }

  
