#!/usr/local/bin/perl

use strict;
use Getopt::Long;

use Bio::Otter::DBSQL::DBAdaptor;

my $host    = 'ecs1d';
my $user    = 'ensadmin';
my $pass    = 'ensembl';
my $dbname  = undef;
my $port    = 19322;

my $min_stable_id = undef;
my $prefix = "OTT";
my $species_prefix = "HUM";

&GetOptions( 'host:s'          => \$host,
             'user:s'          => \$user,
             'pass:s'          => \$pass,
             'port:s'          => \$port,
             'dbname:s'        => \$dbname,
             'minstableid:n'   => \$min_stable_id,
             'prefix:s'        => \$prefix,
             'speciesprefix:s' => \$species_prefix,
            );

if (!defined($dbname)) {
  die "ERROR: Must specify a dbname\n";
}

my $db = new Bio::Otter::DBSQL::DBAdaptor(-host => $host,
                                          -user => $user,
                                          -pass => $pass,
                                          -port => $port,
                                          -dbname => $dbname);

my $meta_con = $db->get_MetaContainer;


if ($min_stable_id) {
  $meta_con->store_key_value('stable_id.min',"$min_stable_id");
}
if ($prefix) {
  $meta_con->store_key_value('prefix.primary',"$prefix");
}
if ($species_prefix) {
  $meta_con->store_key_value('prefix.species',"$species_prefix");
}
