#!/usr/bin/perl

use strict;

use Getopt::Long;

use Bio::Otter::EnsEMBL2SQL::Core;

my $host   = 'kaka.sanger.ac.uk';
my $user   = 'anonymous';
my $pass   = '';
my $port   = 3306;
my $dbname = 'homo_sapiens_core_13_31';
my $chr    = '6';
my $start  = 1;
my $end    = 10000000;
my $type   = 'NCBI31';
my $dir;

&GetOptions( 
             'host:s'    => \$host,
             'user:s'    => \$user,
             'pass:s'    => \$pass,
             'port:s'    => \$port,
             'dbname:s'  => \$dbname,
             'chr:s'     => \$chr,
             'start:n'   => \$start,
             'end:n'     => \$end,
             'type:s'    => \$type,
	     'dir:s'     => \$dir,
             );


my $e2sql = new Bio::Otter::EnsEMBL2SQL::Core(-host   => $host,
					      -user   => $user,
					      -pass   => $pass,
					      -dbname => $dbname,
					      -chr    => $chr,
					      -start  => $start,
					      -end    => $end,
					      -type   => $type);


if (!defined($dir)) {
    $dir = "/tmp/$dbname.$chr.$start-$end.$type";
} 

if (-e $dir) {
    print "Directory $dir exists - exiting\n";
} else {
    mkdir $dir;
}

print "Dumping to directory $dir\n";

my @tables = ('meta',
	      'karyotype',
	      'chromosome',
	      'analysis',
	      'map',
	      'mapset',
	      'interpro',
	      'dnafrag',
	      'external_db',
	      'assembly',
	      'contig',
	      'clone',
	      'dna',
	      'exon',
	      'exon_transcript',
	      'transcript',
	      'translation',
	      'gene',
	      'exon_stable_id',
	      'transcript_stable_id',
	      'translation_stable_id',
	      'gene_stable_id',
	      'dna_align_feature',
	      'protein_align_feature',
	      'simple_feature',
	      'prediction_transcript',
	      'protein_feature',
	      'repeat_feature',
	      'repeat_consensus',
	      'xref',
	      'object_xref',
	      'identity_xref',
	      'external_synonym');

foreach my $table (@tables) {
    $e2sql->dump_SQL_to_file($dir,$table);
}
