#!/usr/local/bin/perl

=head1 DESCRIPTION

get the history comparisons of all versions or particular versions of a gene of a particular stable_id
if output is redirected to file the tab separated output can be opened in excel 

=head1 OPTIONS

can run like this 
~/work/ensembl-otter/scripts/test_history_of_genes -dbhost otterpipe2 -dbport 3323 -dbpass lutralutra -dbuser ottadmin -dbname sp1_human_new_corrected   -stable 'OTTHUMG00000003732'

or this
~/work/ensembl-otter/scripts/test_history_of_genes -dbhost otterpipe2 -dbport 3323 -dbpass lutralutra -dbuser ottadmin -dbname sp1_human_new_corrected  -short -stable 'OTTHUMG00000003732'



=cut

use strict;
use warnings;

use Bio::Vega::DBSQL::DBAdaptor;
use Bio::EnsEMBL::Utils::Exception qw ( throw warning );
use Bio::Vega::Utils::History qw(history);
use Getopt::Long;

my $dbhost;
my $dbport;
my $dbname;
my $dbuser;
my $dbpass;
my $help;
my $short;
my $stable;

$|=1;

&GetOptions(
				'dbhost=s'   => \$dbhost,
				'dbport=n'   => \$dbport,
				'dbname=s'   => \$dbname,
				'dbuser=s'   => \$dbuser,
				'dbpass=s'   => \$dbpass,
				'h|help'     => \$help,
				'stable=s'   => \$stable,
				'short'      => \$short,
			  ) or ($help = 1);


if ($help || !defined ($dbhost) || !defined($dbport) || !defined($dbname) || !defined($dbuser) || !defined($dbpass) || !defined($stable) ) {
  exec('perldoc', $0);
}

##create a db handle
my $db = Bio::Vega::DBSQL::DBAdaptor->new(
														-dbname => $dbname,
														-host   => $dbhost,
														-user   => $dbuser,
														-port   => $dbport,
														-pass   => $dbpass,
													  );



###start working with the actual dump file


my $history;
my $gene_adaptor=$db->get_GeneAdaptor;
my $genes=$gene_adaptor->fetch_all_versions_by_stable_id($stable);
foreach my $gene (@$genes){
  push @$history,$gene;
}

history($history,$short);






1;

