#!/usr/local/bin/perl

### test_lace_client

use strict;
use warnings;

use Getopt::Long 'GetOptions';
use Bio::Otter::Lace::Client;

{
    my $usage = sub{ exec 'perldoc', $0 };
    my $write_flag  = 1;
    my $recover;
    GetOptions(
        'view!'         => sub{ $write_flag = 0 },
        'h|help!'       => $usage,
        'recover=s'     => \$recover,
        ) or $usage->();
    $write_flag = 1 if $recover;

    my $cl = Bio::Otter::Lace::Client->new;
    $cl->host('ecs1d');
    $cl->port(39312);
    $cl->write_access($write_flag);
    
    #my ($ds) = grep $_->name eq 'human_chr20_with_anal_end_feb',
    my $db = $cl->new_AceDatabase;
    $db->title('lace test');
    $db->error_flag(1);

    if ($recover) {
        $db->home($recover);
        $db->recover_slice_dataset_hash;
    } else {
        my $ds = $cl->get_DataSet_by_name('otter_chr9p12');
        my $cs_list = $ds->get_all_CloneSequences;
        $ds->selected_CloneSequences([@$cs_list[2..7]]);
        $db->make_database_directory;
        $db->write_otter_acefile;
        unless ($db->initialize_database) {
            die "Error initialzing database";
        }
    }
    
    system('xace', $db->home);
    
    if ($write_flag) {
        $db->save_all_slices;
    }
    $db->error_flag(0);
}


__END__

=head1 NAME - test_lace_client

=head1 AUTHOR

James Gilbert B<email> jgrg@sanger.ac.uk

