#!/usr/local/bin/perl
$| = 1;
use strict;
use Getopt::Long;

use Bio::Otter::DBSQL::DBAdaptor;
use Bio::Otter::DBSQL::AnnotatedGeneAdaptor;
use Bio::Otter::DBSQL::StableIdAdaptor;
use Bio::Otter::Converter;
use Bio::Otter::Author;

my $host     = 'localhost';
my $user     = 'root';
my $pass     = '';
my $port     = 3306;
my $dbname   = 'test_otter';

my $dna_host   = 'ecs1d';
my $dna_user   = 'ensro';
my $dna_port   = 3306;
my $dna_pass   = undef;
my $dna_dbname = undef;

my $chr      = '1';
my $chrstart = 1;
my $chrend   = 20000000;

my $store;
my $print;

my $acefile;
my $xmlfile;
my $dbfile;

&GetOptions( 'host:s'    => \$host,
             'user:s'    => \$user,
             'pass:s'    => \$pass,
             'port:s'    => \$port,
             'dbname:s'  => \$dbname,
             'dna_host:s'=> \$dna_host,
             'dna_user:s'=> \$dna_user,
             'dna_pass:s'=> \$dna_pass,
             'dna_port:s'=> \$dna_port,
             'dna_dbname:s'  => \$dna_dbname,
             'chr:s'     => \$chr,
             'chrstart:n'=> \$chrstart,
             'chrend:n'  => \$chrend,
             'acefile:s' => \$acefile,
             'xmlfile:s' => \$xmlfile,
             'dbfile:s'  => \$dbfile,
             'store'     => \$store,
             'print'     => \$print);

my $fh;

if ($acefile) {
  open(ACE,"<$acefile");
  $fh = \*ACE;
} elsif ($xmlfile) {
  open(XML,"<$xmlfile");
  $fh = \*XML;
} else {
  die "Must enter an ace file or xml file\n";
}

if ($dbfile) {
  open(DB,"<$dbfile") || die "Can't open $dbfile";
}

my %accession;

while (<DB>) {
  chomp;
  my @f = split(' ',$_);
  $accession{$f[0]} = $f[2];

}
  
  my $odb = new Bio::Otter::DBSQL::DBAdaptor(-host => $host,
                                             -user => $user,
                                             -pass => $pass,
                                             -port => $port,        
                                             -dbname => $dbname);
  if (defined($dna_dbname)) {
    my $dnadb = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host => $dna_host,
                                                 -user => $dna_user,
                                                 -pass => $dna_pass,
                                                 -port => $dna_port,
                                                 -dbname => $dna_dbname);
    $odb->dnadb($dnadb);
  }



my $sgp = $odb->get_SliceAdaptor;
my $ga  = $odb->get_GeneAdaptor;
my $ea  = $odb->get_ExonAdaptor;
my $ta  = $odb->get_TranscriptAdaptor;
my $ida = $odb->get_StableIdAdaptor;
my $ca  = $odb->get_CloneAdaptor;

$odb->begin_work;
$odb->assembly_type('test_otter');

my @genes;
my $chrname;
my $chrstart;
my $chrend;
my $genes;

if ($acefile) {
  ($genes,$chrname,$chrstart,$chrend) = Bio::Otter::Converter::ace_to_otter($fh);
} elsif ($xmlfile) {
  ($genes,$chrname,$chrstart,$chrend) = Bio::Otter::Converter::XML_to_otter($fh,$odb);
}
@genes = @$genes;

if ($print) {
  print "Printing @genes\n";
  foreach my $gene (@genes) {
    print $gene->toXMLString . "\n";
  }
}
if ($store) {  
  my $acc = $accession{$ARGV[0]};
  
  print "Loading $acc $ARGV[0]\n";
  
  if (!defined($acc)) {   
    die " Can't write genes - can't find accession for clone $ARGV[0]\n";
  }
  
  print "acc = $acc argv[0] = " . $ARGV[0] . "\n";
  my $clone = $odb->get_CloneAdaptor->fetch_by_accession($acc);
  my @contigs = @{$clone->get_all_Contigs};
  
  
  if ($#contigs > 0) {
    die "Unfinished clone - can't write genes\n";
  }
  
  if ($#contigs < 0) {
    die "No contig found for clone $acc\n";
  }
  
  my $vcontig = $contigs[0];
  
  my $anal = $odb->get_AnalysisAdaptor()->fetch_by_logic_name('otter');
  my $oaga = $odb->get_GeneAdaptor();
  
  my $name = `whoami`; chomp($name);
  
  my $email = $name . "\@sanger.ac.uk";
  
  my $author = new Bio::Otter::Author(-name => $name, -email => $email);
  my $time = time;
  
  foreach my $gene (@genes) {
    if (!defined($gene->stable_id)) {
       $gene->stable_id($ida->fetch_new_gene_stable_id);
    }
    print "Stable id " . $gene->stable_id . "\n";
  
    $gene->adaptor($ga);
    $gene->analysis($anal);
    $gene->type('otter');
    $gene->gene_info->author($author);
    $gene->created($time);
    $gene->modified($time);
    $gene->version(1);
  
    foreach my $tran (@{$gene->get_all_Transcripts}) {
      if (!defined($tran->stable_id)) {
         $tran->stable_id($ida->fetch_new_transcript_stable_id);
      }
      $tran->adaptor($ta);
      $tran->transcript_info->author($author);
      $tran->created($time);
      $tran->modified($time);
      $tran->version(1);
      
    }
    my $count = 1;
  
    foreach my $exon (@{$gene->get_all_Exons}) {
      if (!defined($exon->stable_id)) {
         $exon->stable_id($ida->fetch_new_exon_stable_id);
      }

      $exon->contig($vcontig);
      $exon->adaptor($ea);
      $exon->created($time);
      $exon->modified($time);
      $exon->version(1);
  
      $count++;
    }
    foreach my $tran (@{$gene->get_all_Transcripts}) {
      $tran->sort;
      print "Transcript " . $tran->stable_id . " class " . $tran->transcript_info->class->name . "\n";
      if ($tran->translation) { 
        print "Translation " . $tran->translation->start_Exon->stable_id . "\t" . $tran->translation->start . "\n";
        print "Translation " . $tran->translation->end_Exon->stable_id . "\t" . $tran->translation->end . "\n";
        foreach my $exon (@{$tran->get_all_Exons}) {
	    print "Exon " . $exon->stable_id . "\t" . $exon->start . "\t" . $exon->end . "\t" . $exon->strand . 
                 "\t" . $exon->phase . "\t" . $exon->end_phase . "\n";
        }
        print "Translation " . $tran->stable_id . " " . $tran->translate->seq . "\n";
      } else {
        print "No translation for " . $tran->stable_id . "\n";
      }
    }
    $oaga->store($gene);
  }
}
$odb->commit;
