#!/bin/sh

#for i in ../tgz/*gz  ; do
   i=$1
   f=${i%.tar.gz}
   echo $f
   gunzip -c $i |tar xvf -
   g=${f#../tgz/}
   cd $g
   perl Makefile.PL
   make
   make test
   make install
   cd ..
#done 
